---
settings:
  name: Release notes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
    - workload-fsx-ontap
    - 
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Workload Factoryリリースノート
    url: "/index.html"
  - title: 最近の変更
    url: "/whats-new.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: Workload Factory
  repo: workload-family
