---
settings:
  name: Release notes
  rss_page: whats-new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
    - workload-fsx-ontap
    - workload-databases
    - workload-vmware
    - workload-genai
    - workload-setup-admin
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP  ワークロード工場出荷時のリリースノート
    url: "/index.html"
  - title: 最近の変更
    url: "/whats-new.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
