---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: BlueXP  ワークロードファクトリに含まれているワークロードに対する最新の変更について説明します。 
---
= BlueXP  ワークロードファクトリにおける最近の変更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリに含まれているワークロードに対する最新の変更について説明します。



== 2025年5月04日



=== NetApp ONTAP 対応の Amazon FSX



==== FSx for ONTAPファイルシステム向け自律型ランサムウェア対策

自律型ランサムウェア対策（ARP）でデータを保護：NAS（NFS / SMB）環境でワークロードを分析し、ランサムウェア攻撃の可能性がある異常なアクティビティを検出して警告する機能です。攻撃が疑われると、ARPは変更不可能な新しいスナップショットも作成し、そこからデータを復元できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["自律型ランサムウェア対策でデータを保護"]



==== FlexGroupボリュームのリバランシングの強化

BlueXP  ワークロード工場出荷時に導入されたFlexGroupボリュームリバランシングウィザードには、FlexGroupボリューム内のデータをリバランシングするためのいくつかのレイアウトオプションが用意されています。リバランシングを実行すると、FlexGroupメンバーボリュームにデータが均等に再配分されます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["FlexGroupボリューム内の容量のリバランシング"]



==== FSx for ONTAPファイルシステムのベストプラクティスを実装

BlueXP  ワークロードファクトリには、ファイルシステム構成の適切な設計ステータスを確認できるダッシュボードが用意されています。この分析を活用して、FSx for ONTAPファイルシステムのベストプラクティスを実装できます。ファイルシステム構成の分析には、SSD容量のしきい値、スケジュールされたローカルスナップショット、FSx for ONTAPのスケジュールされたバックアップ、データ階層化、リモートデータレプリケーションなどの構成が含まれます。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["ファイルシステム構成の適切に設計された分析をご紹介します"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ファイルシステムのベストプラクティスの実装"]




==== デュアルプロトコルボリュームのセキュリティ形式のオプション

ボリュームのセキュリティ形式としてNTFSまたはUNIXを選択して、ユーザや権限がボリュームにアクセスする方法を決定できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["ボリュームの作成"]



==== レプリケーションの機能拡張



===== FSx for ONTAPからオンプレミスへのリバースレプリケーションをサポート

FSx for ONTAPファイルシステムからオンプレミスのONTAPクラスタへのリバースレプリケーションを、ワークロードファクトリコンソールから利用できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["リバースレプリケーション"]



===== データ保護ボリュームのレプリケーション

データ保護ボリュームをレプリケートできるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["データ保護ボリュームをレプリケートする"]



===== 複数ボリュームの選択

複数のボリュームを選択できるため、レプリケートするボリュームを正確に選択できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["レプリケーション関係を作成する"]



===== 長期保持ポリシーのラベル

レプリケーション関係に対して長期保持を有効にする場合は、ソースボリュームとターゲットボリュームのラベルが完全に一致している必要があります。BlueXP  ワークロードファクトリで、欠落しているソースボリュームラベルが自動的に作成されるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["レプリケーション関係を作成する"]



==== FSx for ONTAPのファイル名がボリューム作成時に表示される

FSx for ONTAPファイルシステムのボリューム作成時の可視性が向上しました。ボリュームを作成するとFSx for ONTAPファイルシステムが表示されるため、ボリュームが作成されている場所を正確に把握できます。



==== ストレージワークロード全体でAWSアカウントを認識

ストレージワークロード全体のアカウントの可視性が向上しました。AWSアカウントは、*[ボリューム]*、*[Storage VM]*、*[レプリケーション]*の各タブに移動すると表示されます。



==== リンクアソシエーションの機能拡張

* FSx for ONTAPファイルシステムからのリンクは、[インベントリ]タブで簡単に関連付けることができます。
* BlueXP  ワークロードファクトリでは、リンクの関連付けに代替ONTAPユーザクレデンシャルの使用がサポートされるようになりました。




==== AWS Secrets Managerのリンク認証のサポート

AWS Secrets Managerのシークレットを使用してリンクを認証できるようになり、BlueXP  ワークロードファクトリに保存されているクレデンシャルを使用する必要がなくなりました。



==== トラッカー応答サポート

TrackerでAPI応答が返されるようになり、タスクに関連するREST API出力を確認できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Trackerを使用した操作の監視"]



==== バックアップからボリュームをリストアする際の容量の検証

バックアップからボリュームをリストアする場合、BlueXP  ワークロードの工場出荷時にリストアに十分な容量があるかどうかが確認され、十分でない場合はSSDストレージ階層の容量が自動的に追加されます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["バックアップからボリュームをリストアする"]



==== 代替ONTAPユーザクレデンシャルのサポート

Workload Factoryでは、ファイルシステムを作成するためのONTAPクレデンシャルの代替セットがサポートされるようになりました。fsxadminユーザだけを使用する代わりに、別のONTAPクレデンシャルのセットを選択するか、fsxadminユーザとvsaadminユーザのパスワードを指定しないように選択できます。



==== 権限に関する用語を更新

ワークロードファクトリのユーザインターフェイスとドキュメントでは、読み取り権限を「読み取り専用」に、自動権限を「読み取り/書き込み」に指定するようになりました。



=== データベースワークロード



==== ダッシュボードの機能拡張

* BlueXP  ワークロードファクトリコンソールのタブ間を移動すると、アカウント間ビューとリージョン間ビューを使用できます。新しいビューは、リソースの管理、監視、最適化を改善します。
* ダッシュボードの* Potential Savings *タイルから、Amazon Elastic Block StoreまたはAmazon FSx for WindowsファイルサーバからFSx for ONTAPに切り替えることで、削減可能なコストをすばやく確認できます。




==== データベース構成で使用可能なアドホックスキャン

BlueXP  Workload Factory for Databasesは、管理対象のMicrosoft SQL ServerインスタンスをFSx for ONTAPストレージで自動的にスキャンし、潜在的な構成の問題がないかどうかを確認します。毎日のスキャンに加えて、いつでもスキャンできます。



==== オンプレミス評価記録の削除

オンプレミスのMicrosoft SQL Serverホストの削減効果を確認したら、オンプレミスのホストレコードをBlueXP  ワークロードファクトリから削除することもできます。



==== 最適化の機能拡張



===== クローンのクリーンアップ

クローンクリーンアップの評価と修正では、コストのかかる古いクローンを特定して管理します。60日を経過したクローンは、BlueXP  ワークロードファクトリコンソールで更新または削除できます。



===== 構成分析の延期と却下

一部の設定はデータベース環境に適用されない場合があります。特定の構成分析を30日延期するか、分析を却下するかを選択できるようになりました。



==== オンプレミス評価記録の削除

オンプレミスのMicrosoft SQL Serverホストの削減効果を確認したら、オンプレミスのホストレコードをBlueXP  ワークロードファクトリから削除することもできます。



==== 権限に関する用語を更新

ワークロードファクトリのユーザインターフェイスとドキュメントでは、読み取り権限を「読み取り専用」に、自動権限を「読み取り/書き込み」に指定するようになりました。



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* NetAppデータインフラのインサイトをデータソースとして*：ワークロードファクトリは、EC2移行アドバイザのデータコレクタを使用すると、NetAppデータインフラのインサイトに直接接続して、VMwareの導入情報を収集できるようになりました。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



==== 権限に関する用語を更新

ワークロードファクトリのユーザインターフェイスとドキュメントでは、読み取り権限を「読み取り専用」に、自動権限を「読み取り/書き込み」に指定するようになりました。



=== 生成AIワークロード



==== Amazon Q向けNetApp ONTAP Connectorのサポート

このリリースの 生成AIでは、NetApp ONTAP Connector for Amazon Qのサポートが導入され、Amazon Q Business用のコネクタを作成できるようになりました。Amazon Bedrock用の 生成AIナレッジベースを構築するよりも、初期設定が少なくて済み、Amazon Q Business AIアシスタントをすばやく簡単に活用できます。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Amazon Q Business用の 生成AIコネクタの作成"]



==== 強化されたチャットモデルサポート

生成AIでは、ナレッジベース用に次の追加チャットモデルがサポートされるようになりました。

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AIモデル"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titanテキストモデル"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llamaモデル"^]
* link:https://docs.ai21.com/["Jamba 1.5モデル"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohereコマンドモデル"^]
* link:https://aws.amazon.com/bedrock/deepseek/["ディープシークモデル"^]


生成AIは、Amazon Bedrockがサポートする各プロバイダのモデルをサポートしています。link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon Bedrockでサポートされる基盤モデル"^]

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html["生成AIナレッジベースの作成"]



==== 権限に関する用語を更新

ワークロードファクトリのユーザインターフェイスとドキュメントでは、読み取り権限を「読み取り専用」に、自動権限を「読み取り/書き込み」に指定するようになりました。



=== セットアップと管理



==== CloudShellオートコンプリートのサポート

BlueXP  ワークロードファクトリCloudShellを使用している場合は、コマンドの入力を開始してTabキーを押すと、使用可能なオプションが表示されます。複数の候補が存在する場合は、CLIに候補のリストが表示されます。この機能は、エラーを最小限に抑え、コマンド実行を高速化することで、生産性を向上させます。



==== 権限に関する用語を更新

ワークロードファクトリのユーザインターフェイスとドキュメントでは、読み取り権限を「読み取り専用」に、自動権限を「読み取り/書き込み」に指定するようになりました。



== 2025年4月04日



=== データベースワークロード



==== 最適化の機能拡張

データベース環境を最適化する際に、新しい最適化評価、修正、複数のリソースの表示を利用できます。



===== 耐障害性の評価

強化された機能には、データベース環境に対してデータの冗長性とディザスタリカバリ機能が設定されているかどうかをチェックするための新しい耐障害性評価が含まれています。

* FSx for ONTAPバックアップ：SQL Serverインスタンスのボリュームを提供するFSx for ONTAPファイルシステムが、定期的なFSx for ONTAPバックアップで設定されているかどうかを分析します。
* リージョン間レプリケーション：Microsoft SQL Serverインスタンスを提供するFSx for ONTAPファイルシステムでリージョン間レプリケーションが設定されているかどうかを評価します。




===== コンピューティングの修正

受信側スケーリング（RSS）修正は、ネットワーク処理を複数のプロセッサに分散し、効率的な負荷分散を確保するようにRSSを構成します。



===== ローカルSnapshotの修正

ローカルSnapshotの修正では、データ損失が発生した場合にデータベース環境の耐障害性を維持するために、Microsoft SQL ServerインスタンスのボリュームのSnapshotポリシーを設定します。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



===== 複数リソース選択のサポート

データベース設定を最適化する際に、すべてのリソースではなく特定のリソースを選択できるようになりました。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



==== インベントリビューの改善

ワークロードファクトリコンソールの[Inventory]タブは合理化され、Amazon FSx for NetApp ONTAPで実行されるSQLサーバのみが含まれるようになりました。SQLサーバーはオンプレミスで、Amazon Elastic Block StoreとAmazon FSx for Windows File Serverで稼働しています。



==== PostgreSQLサーバー展開で利用可能なクイック作成

この迅速な導入オプションを使用すると、HA構成とベストプラクティスが組み込まれたPostgreSQLサーバを作成できます。

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["BlueXP  ワークロードファクトリでPostgreSQLサーバを作成する"]



== 2025年3月30日



=== NetApp ONTAP 対応の Amazon FSX



==== スケールアウトシステムの容量を自動管理

Workload factoryでは、ボリューム内の使用可能なinodeがスキャンされ、設定された容量の自動管理しきい値に従ってその数が増加します。この機能では、スケールアウトシステムの容量の自動管理がサポートされます。容量の自動管理の一環として、inode管理を有効にすることができます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["容量の自動管理を有効にする"]



==== FlexGroupリバランシングAPI

BlueXP  ワークロード工場では、FlexGroupリバランシングAPIがリリースされています。このAPIを使用すると、FlexGroup内のデータをリバランシングするプランを実行できます。リバランシングを実行すると、メンバーボリュームにデータが均等に再配分されます。

link:https://console.workloads.netapp.com/api-doc["BlueXP  ワークロードファクトリAPIドキュメント"]



==== データの複製フォームにはユースケースが含まれる

データの複製フォームには、フォームへの入力を容易にするためのユースケースが含まれるようになりました。データレプリケーションのユースケースとして、移行、ホットディザスタリカバリ、コールドディザスタリカバリ、アーカイブなどのいずれかを選択します。ユースケースを選択したあと、Workload Factoryではベストプラクティスに従った値が推奨されます。事前選択された値を受け入れるか、フォームの値をカスタマイズできます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["データのレプリケート"]



==== データ階層化ポリシーの用語の変更

ボリュームの作成時、データレプリケーション時、または既存の階層化ポリシーの更新時に階層化ポリシーを選択すると、階層化ポリシーを表す新しい用語が追加されます。

* バランス（自動）_
* _コスト最適化（すべて）_
* _パフォーマンスを最適化（Snapshotのみ）_




==== ファイルシステム作成のセキュリティグループの詳細

セキュリティグループは、FSx for ONTAPファイルシステムの作成プロセスの一環として作成されます。セキュリティグループの詳細（プロトコル、ポート、ロールなど）を確認できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["ファイルシステムの作成"]



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* *ボリューム割り当てガイダンスの強化*：EC2 Migration Advisorの「Classify」および「Package」ステップのボリューム割り当て情報には、読みやすさと操作性が向上しています。各ボリュームについて、より有益な情報が表示されるため、ボリュームの特定や割り当て方法の決定に役立ちます。
* *データコレクタスクリプトの効率化*: EC2移行アドバイザのデータコレクタスクリプトは、小規模なVM環境でデータを収集する際のCPU使用率を最適化します。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



=== 生成AIワークロード



==== ファイル形式のサポートの強化

このリリースの 生成AIでは、データソースからファイルを取り込む際のJSONおよびJSONPファイル形式のサポートが導入されて `.json`います。ネストされたオブジェクトを含むJSONファイルがサポートされますが、ネストされた配列はサポートされません。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["サポートされるデータソースファイル形式"]



==== 外部チャットボットサンプルアプリケーションの国際化サポート

生成AIサンプル外部チャットボットアプリケーションのユーザーインターフェイスを別の言語やロケールに簡単に変更できるようになりました。

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["生成AI外部サンプルチャットボットアプリケーション"]



==== Anthropic Claude Sonnet 3.7チャットモデルのサポート

生成AIでは、Anthropic Claude 3.7 Sonnetチャットモデルがサポートされるようになりました。Claude 3.7 Sonnetのベータ機能は、要求ごとに最大128Kの出力トークンを可能にし、新しいコンピュータの使用アクションをサポートします。Claude 3.7 Sonnet拡張思考モードは、将来の 生成AIリリースでサポートされる予定です。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



==== 汎用NFS / SMB共有からのデータソースの追加のサポート

ワークロードファクトリAPIを使用して、一般的なNFSv3、NFSv4、またはSMB共有からデータソースを追加できるようになりました。NFS共有またはSMB共有からデータソースを追加しても、ナレッジベースボリュームはAmazon FSx for NetApp ONTAPボリュームに残ります。この機能は、ワークロードファクトリのWeb UIで今後のリリースでサポートされる予定です。

link:https://console.workloads.netapp.com/api-doc["ワークロードファクトリAPIを使用"^]



==== vPCピアリングのサポート

同じリージョンにあるに 生成AIインフラを導入し、同じAWSアカウントを使用できるようになりましlink:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["ピア関係にある仮想プライベートクラウド（VPC）"^]た。AIエンジンをVPCに導入してから、ピアVPCにナレッジベースを作成し、ピアVPCにあるAmazon FSx for NetApp ONTAPファイルシステムを選択できます。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



=== セットアップと管理



==== ONTAP CLIコマンドについて、AIによって生成されたエラー応答がCloudShellで報告される

CloudShellを使用している場合、ONTAP CLIコマンドを発行してエラーが発生するたびに、失敗の説明、失敗の原因、詳細な解決策を含むAI生成のエラー応答を取得できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用"]



==== IAM：SimulatePermissionPolicy権限の更新

AWSアカウントのクレデンシャルを追加したり、生成AIワークロードなどの新しいワークロード機能を追加したりするときに、ワークロードファクトリコンソールから権限を管理できるようになりまし `iam:SimulatePrincipalPolicy`た。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]



== 2025年3月03日



=== データベースワークロード



==== PostgreSQLの高可用性構成

PostgreSQLサーバにハイアベイラビリティ（HA）構成を導入できるようになりました。

link:https://review.docs.netapp.com/us-en/workload-databases_explore-savings-updates/create-postgresql-server.html["PostgreSQLサーバの作成"]



==== PostgreSQLサーバ作成のTerraformサポート

CodeboxからTerraformを使用してPostgreSQLをデプロイできるようになりました。

* link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["PostgreSQLデータベースサーバの作成"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["コードボックスからTerraformを使用"]




==== ローカルSnapshotスケジュールの耐障害性評価

データベースワークロードに新しい耐障害性評価を提供します。Microsoft SQL Serverインスタンスのボリュームにスケジュールされた有効なSnapshotポリシーが設定されているかどうかを評価します。Snapshotは、データのポイントインタイムコピーであり、データ損失が発生した場合にデータベース環境の耐障害性を維持するのに役立ちます。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



==== MAXDOPによるデータベースワークロードの修正

BlueXP  Workload Factory for Databasesでは、最大並列化(MAXDOP)サーバ構成の修復がサポートされるようになりました。MAXDOP設定が最適でない場合、BlueXP  Workload Factoryに設定を最適化させることができます。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



==== コスト削減分析レポートをEメールで送信

Amazon Elastic Block StoreとFSx for Windowsファイルサーバのストレージ環境でFSx for ONTAPと比較してコスト削減を検討している場合、推奨レポートを自分、チームメンバー、お客様にEメールで送信できるようになりました。



== 2025年3月02日



=== NetApp ONTAP 対応の Amazon FSX



==== 容量管理の自動化の強化

容量の自動管理を有効にすると、BlueXP  ワークロードファクトリでは、ファイルシステムが容量のしきい値に達したかどうかが2時間ごとではなく30分ごとにチェックされるようになりました。

容量のしきい値に達しても、プロビジョニングIOPSの設定は影響を受けなくなりました。



==== 変更不可のSnapshot

特定の保持期間にわたってSnapshotをロックし、変更不可にすることができるようになりました。ロックにより、スナップショットへの不正アクセスや悪意のある削除を防止できます。Snapshotポリシーの作成時、手動でのSnapshotの作成時、およびSnapshotの作成後に、変更不可のSnapshotを有効にすることができます。



==== 不変ファイルの更新

変更不可のファイル設定に対して、保持ポリシー、保持期間、自動コミット期間、およびボリュームアペンドモードを変更できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["変更不可ファイルの管理"]



==== データレプリケーションの機能拡張

* アカウント間レプリケーション：2つのAWSアカウント間のレプリケーションは、BlueXP  ワークロードファクトリコンソールとレプリケーション管理でサポートされています。
* レプリケーションの一時停止と再開：ソースボリュームからデスティネーションボリュームへのスケジュールされたレプリケーション更新を一時停止（休止）し、準備ができたらレプリケーションスケジュールを再開できます。一時停止中は、ソースボリュームとデスティネーションボリュームが独立し、デスティネーションボリュームは読み取り専用から読み書き可能に移行します。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["レプリケーション関係の一時停止と再開"]





==== TrackerのCloudShellイベント

これで、TrackerでCloudShellイベントを追跡できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Trackerを使用して運用を監視および追跡する方法をご確認ください"]



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* *推定インスタンスタイプ*：Migration Advisorで環境の要件を確認し、VMごとに推定Amazon EC2インスタンスタイプを提供できるようになりました。移行アドバイザの「スコープ」ステップで、各VMの推定インスタンスタイプを含めるように選択できます。
* * Amazon EBSボリュームの推奨機能*：移行アドバイザーは、特定のリージョンの容量やパフォーマンスのニーズに応じて、Amazon FSx for NetApp ONTAPではなくAmazon Elastic Block Store（EBS）にデータボリュームを移行することを推奨できるようになりました。
* *ファイルシステムの自動割り当ての強化*：Amazon FSx for NetApp ONTAPファイルシステムの割り当てが改善され、コストの最適化とスループットの最小化が実現しました。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



=== 生成AIワークロード



==== 組み込みチャットボットの機能強化

質問と回答をクリップボードに直接コピーしたり、チャットウィンドウのサイズを調整したり、タイトルを変更したりできるようになりました。さらに、チャット応答にテーブルを含めることができるようになりました。テーブルはコピー可能です。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["生成AIナレッジベースのテスト"]



==== チャット応答引用のサポート

チャットの応答に、応答を生成するために使用されたファイルとデータのチャンクをリストする引用が含まれるようになりました。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/test-knowledgebase.html["生成AIナレッジベースのテスト"]



==== ファイル形式のサポートの強化

このリリースの 生成AIでは、ファイルサポートが強化されています。

* チャットモデル機能CSVサポートが改善されました。これにより、CSVファイルからデータを照会するときに、より便利な応答が可能になります。
* 生成AIは、データソースからApache Parquetファイルを取り込むことができるようになりました。
* 生成AIでは、画像を含むMicrosoft Word DOCXファイルの取り込みがサポートされるようになりました。DOCXドキュメント内に埋め込まれた画像がスキャンされ、埋め込まれた画像からのテキストインサイトがナレッジベースのクエリへの応答に含まれます。


link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["サポートされるデータソースファイル形式"]



== 2025年02月02日



=== セットアップと管理



==== BlueXP  Workload FactoryコンソールでCloudShellを使用可能

CloudShellは、BlueXP  ワークロードファクトリコンソールのどこからでも使用できます。CloudShellを使用すると、BlueXP  アカウントで提供したAWSとONTAPのクレデンシャルを使用して、シェルに似た環境でAWS CLIコマンドまたはONTAP CLIコマンドを実行できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用"]



==== データベースの権限の更新

データベースの_read_modeで次の権限を使用できるようになりました `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]
