---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: BlueXP  ワークロードファクトリに含まれているワークロードに対する最新の変更について説明します。 
---
= BlueXP  ワークロードファクトリにおける最近の変更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリに含まれているワークロードに対する最新の変更について説明します。



== 2025年6月30日



=== データベースワークロード



==== BlueXPワークロードファクトリー通知サービスのサポート

BlueXP ワークロードファクトリー通知サービスを使用すると、ワークロードファクトリーは BlueXP アラートサービスまたは Amazon SNS トピックに通知を送信できます。BlueXPアラートに送信された通知は、BlueXP アラートパネルに表示されます。ワークロードファクトリーが Amazon SNS トピックに通知を発行すると、トピックのサブスクライバー（ユーザーや他のアプリケーションなど）は、トピックに設定されたエンドポイント（E メールや SMS メッセージなど）で通知を受け取ります。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXPワークロードファクトリー通知を構成する"^]

ワークロード ファクトリーは、データベースに対して次の通知を提供します。

* よく設計されたレポート
* ホストの展開




==== インスタンス登録のオンボーディング強化

Workload Factory for Databases は、Amazon FSx for NetApp ONTAP ストレージ上で稼働するインスタンスの登録プロセスを改善しました。これにより、登録するインスタンスを一括で選択できるようになりました。インスタンスが登録されると、ワークロード ファクトリー コンソール内でデータベース リソースを作成および管理できるようになります。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["インスタンス管理"]



==== Microsoft マルチパス I/O タイムアウト設定の分析と修正

データベース インスタンスの well-architected ステータスに、Microsoft Multipath I/O (MPIO) タイムアウト設定の分析と修正が含まれるようになりました。タイムアウトを60秒に設定することで、FSx for ONTAPストレージの接続性とフェイルオーバー時の安定性が確保されます。MPIO設定が適切に設定されていない場合は、ワークロードファクトリーがMPIOタイムアウト値を60秒に設定する修正を提供します。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["ワークロードファクトリーで適切に設計されたデータベース構成を実装する"]



==== インスタンスインベントリのグラフィックの強化

インスタンス インベントリ画面では、スループットや IOPS などのさまざまなリソース使用率グラフに 7 日間のデータが表示されるようになり、ワークロード ファクトリー コンソールから SQL ノードのパフォーマンスをより効率的に監視できるようになりました。ノードから収集されたパフォーマンスメトリクスはAmazon CloudWatchに保存され、Logs Insightsや環境内の他の分析サービスとの統合に使用できます。

インベントリ内のインスタンスとデータベースのタブでは、保護の説明と視覚化が強化されました。



==== ワークロードファクトリーでの Windows 認証のサポート

現在、ワークロード ファクトリーは、インスタンスを登録し、管理機能のメリットを享受するために、Windows 認証ユーザーを使用した SQL Server 認証をサポートしています。

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["データベースのワークロードファクトリーにインスタンスを登録する"]



== 2025年6月29日



=== NetApp ONTAP 対応の Amazon FSX



==== BlueXPワークロードファクトリー通知サービスのサポート

BlueXP ワークロードファクトリー通知サービスを使用すると、ワークロードファクトリーは BlueXP アラートサービスまたは Amazon SNS トピックに通知を送信できます。BlueXPアラートに送信された通知は、BlueXP アラートパネルに表示されます。ワークロードファクトリーが Amazon SNS トピックに通知を発行すると、トピックのサブスクライバー（ユーザーや他のアプリケーションなど）は、トピックに設定されたエンドポイント（E メールや SMS メッセージなど）で通知を受け取ります。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXPワークロードファクトリー通知を構成する"^]



==== ストレージダッシュボードの機能強化

ワークロードファクトリーコンソールのストレージダッシュボードに、コスト削減の機会を示す新しいカードが追加されました。ダッシュボード上部のカードには、Amazon Elastic Block Store (EBS)、Amazon FSx for Windows File Server、Amazon Elastic File Systems (EFS) で実行されているストレージ環境におけるコスト削減の機会の数が表示されます。ダッシュボード下部には、Amazon ストレージサービス (EBS、FSx for Windows File Server、EFS) ごとのコスト削減の機会を示す 3 つの新しいカードが追加されました。すべてのカードから、コスト削減の機会をより詳細に確認できます。

FSx for ONTAP の保護範囲カードとレプリケーション関係の健全性カードから、FSx for ONTAP ファイルシステム内に部分的に保護されているボリュームがあるかどうか、またレプリケーション関係に関する問題を調査できます。どちらの場合も、問題を解決するためのアクションを実行できます。



==== 音量タブの機能強化

ワークロードファクトリーコンソールの「ボリューム」タブが強化され、FSx for ONTAPファイルシステムのより包括的なビューが提供されるようになりました。強化された機能には、SSD容量、容量プール、NetApp Autonomous Ransomware Protection with AI（ARP/AI）の新しいカードが含まれます。これらのカードには、ファイルシステム内のすべてのボリュームの容量使用率とARP/AI保護の概要が表示されます。



==== 第2世代のAmazon FSx for NetApp ONTAPファイルシステムをサポート

ワークロードファクトリーは、第2世代Amazon FSx for NetApp ONTAPファイルシステムのサポートを開始しました。ワークロードファクトリーコンソールで、第2世代ファイルシステムの作成、管理、モニタリングが可能です。すべての新しい商用リージョンがサポートされています。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["ワークロードファクトリーで第2世代のファイルシステムを作成する"]



==== ボリューム容量の再バランス調整のためのFlexVolボリュームのサポート

FlexVolは、ワークロードファクトリーコンソール内で検出できます。FlexVolのバランスを確認し、新規ファイルの追加やファイルの増加によって時間の経過とともに不均衡が生じた場合は、FlexVolをリバランスして容量を再配分できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["FlexVolボリュームの容量を再調整する"]



==== 用語の更新

ワークロード ファクトリー コンソールで、「Autonomous Ransomware Protection」(ARP) という用語が「NetApp Autonomous Ransomware Protection with AI」(ARP/AI) に更新されました。



==== 新しいボリュームでは ARP/AI がデフォルトで有効になっています

ワークロードファクトリーコンソールで新しいボリュームを作成すると、ファイルシステムにARP/AIポリシーが設定されている場合、NetApp Autonomous Ransomware Protection with AI（ARP/AI）がデフォルトで有効化されます。つまり、ボリュームはAIを活用した検出・対応機能によってランサムウェア攻撃から自動的に保護されます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["ワークロードファクトリーでボリュームを作成する"]



==== 不変ファイルのレプリケーションサポート

ワークロードファクトリーは、FSx for ONTAP システム間で不変ボリュームを複製し、重要なデータを誤削除やランサムウェアなどの悪意のある攻撃から保護します。複製先のボリュームとそのホストファイルシステムは不変（ロック）状態となり、保持期間が終了するまで、複製先のファイルシステム内のデータは変更または削除できません。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["レプリケーション関係を作成する方法を学ぶ"]



==== リンク作成中にIAM実行ロールと権限を管理する

ワークロードファクトリーコンソールでリンクを作成する際に、IAM 実行ロールとそれに紐付けられた権限ポリシーを管理できるようになりました。リンクは、ワークロードファクトリーアカウントと 1 つ以上の FSx for ONTAP ファイルシステム間の接続を確立します。IAM実行ロールとリンク権限の割り当てには、自動割り当てとユーザー指定の 2 つのオプションがあります。ワークロードファクトリーで実行ロールとそれに紐付けられた権限ポリシーを管理することで、サードパーティ製のコードを使用する必要がなくなります。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["LambdaリンクでFSx for ONTAPファイルシステムに接続"]



=== VMwareワークロード



==== Amazon Elastic VMWare Service の移行アドバイザーサポートの導入

BlueXPのVMware向けワークロードファクトリーが、Amazon Elastic VMware Serviceをサポートするようになりました。移行アドバイザーを使用することで、オンプレミスのVMwareワークロードをAmazon Elastic VMware Serviceに迅速に移行できます。これにより、アプリケーションのリファクタリングやプラットフォーム変更を行うことなく、コストを最適化し、VMware環境をより細かく制御できるようになります。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["移行アドバイザーを使用して Amazon EVS のデプロイメント計画を作成する"]



=== 生成AIワークロード



==== 汎用 NFS/SMB ファイルシステムでホストされるデータソースのサポート

汎用SMBまたはNFS共有からデータソースを追加できるようになりました。これにより、Amazon FSx for NetApp ONTAP以外のファイルシステムでホストされているボリュームに保存されているファイルも含めることができます。

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["ナレッジベースにデータソースを追加する"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["コネクタにデータソースを追加する"]



=== セットアップと管理



==== データベースの権限の更新

データベースの _読み取り専用_ モードで次の権限が利用できるようになりました。  `cloudwatch:GetMetricData` 。

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]



==== BlueXPワークロードファクトリー通知サービスのサポート

BlueXP ワークロードファクトリー通知サービスを使用すると、ワークロードファクトリーは BlueXP アラートサービスまたは Amazon SNS トピックに通知を送信できます。BlueXPアラートに送信された通知は、BlueXP アラートパネルに表示されます。ワークロードファクトリーが Amazon SNS トピックに通知を発行すると、トピックのサブスクライバー（ユーザーや他のアプリケーションなど）は、トピックに設定されたエンドポイント（E メールや SMS メッセージなど）で通知を受け取ります。

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXPワークロードファクトリー通知を構成する"]



== 2025年6月16日



=== ビルダーのワークロード



==== クローンサポート

BlueXP Workload Factory for Builders でプロジェクトのクローンを作成できるようになりました。プロジェクトのクローンを作成すると、Builders はスナップショットから、元のプロジェクトと同じ構成の新しいプロジェクトを作成します。クローン作成は、類似のプロジェクトを素早く作成したり、テスト目的で使用する場合に便利です。新しいプロジェクトのクローンは、Builders の指示に従ってマウントできます。

https://docs.netapp.com/us-en/workload-builders/version-projects.html["ビルダープロジェクトの BlueXP ワークロード ファクトリーのバージョンを管理する"]



== 2025年6月08日



=== NetApp ONTAP 対応の Amazon FSX



==== 問題解決のための新しい優れた分析とサポート

FSx for ONTAP ファイルシステムの自動容量管理が、Well-Architected ステータス ダッシュボードの構成分析として含まれるようになりました。

さらに、ワークロード ファクトリーでは、次の構成の問題の修正がサポートされるようになりました。

* SSD容量しきい値
* データの階層化
* スケジュールされたローカルSnapshot
* FSx for ONTAP バックアップ
* リモートデータレプリケーション
* ストレージの効率化
* 自動容量管理


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["構成の問題を修正する"]



== 2025年6月03日



=== NetApp ONTAP 対応の Amazon FSX



==== ボリューム自動拡張の強化

ビジネス ニーズやアプリケーション要件に応じて、ボリューム サイズがプロビジョニングされたサイズを超えて拡張できるように、ボリュームの自動拡張サイズを設定できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["ボリュームの自動拡張を有効にする"]



==== Well-Architected 分析のアップデート

Workload Factory は、FSx for ONTAP ファイルシステムを分析し、データコンパクション、圧縮、重複排除といったストレージ効率が活用されているかどうかを確認します。ストレージ効率は、ファイルシステムが利用可能なスペースをどれだけ効率的に使用しているかを測定します。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ストレージ効率の適切なアーキテクチャの状態を表示する"]



==== ストレージダッシュボードの機能強化

本日より、ワークロードファクトリーコンソールからストレージワークロードを開くと、*ダッシュボード*が表示されます。新しく設計されたダッシュボードでは、ファイルシステムの数、SSDの総容量、Well-Architectedステータスの概要、データ保護の概要、レプリケーション関係の健全性など、FSx for ONTAPシステムの包括的なビューを提供します。



==== ボリュームタブの機能強化

ストレージワークロードでは、ワークロードファクトリーコンソールのFSx for ONTAPファイルシステム内の「ボリューム」タブが強化されました。強化された内容は次のとおりです。

* *新しいカード*: SSD 容量、容量プール、自律ランサムウェア保護 (ARP)
* *新しい列*: 容量分布、使用済み SSD 容量、使用済み容量プール、SSD 効率




==== ボリューム作成時のストレージ効率のアップデート

新しいボリュームを作成すると、データの圧縮、圧縮、重複排除などのストレージ効率がデフォルトで有効になります。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["ワークロードファクトリーに新しいボリュームを作成する"]



=== データベースワークロード



==== PostgreSQLとOracleの検出

ワークロードファクトリーコンソール内で、AWSアカウントでPostgreSQLサーバーデータベースとOracleデータベースデプロイメントを実行しているインスタンスを検出できるようになりました。検出されたインスタンスはデータベースインベントリに表示されます。



==== 「最適化」の用語を更新しました

以前は「最適化」と呼ばれていたワークロード ファクトリーでは、現在、「well-architected の問題」と「well-architected ステータス」を使用してデータベース構成の分析を説明し、「修正」を使用してベスト プラクティスの推奨事項を満たすようにデータベース構成を改善する機会の修復を説明します。

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["ワークロードファクトリーにおけるデータベース環境の構成分析"]



==== インスタンスのオンボーディングの改善

インスタンス管理において「未検出」「管理対象外」「管理対象」といった用語が使用されるのに対し、ワークロードファクトリーではインスタンスのオンボーディングに「登録」という用語を使用するようになりました。新しい登録プロセスには、インスタンスの認証と準備が含まれており、ワークロードファクトリーコンソール内でデータベース構成のリソースを作成、監視、分析、修正できるようになります。登録プロセスの準備手順は、インスタンスが管理の準備ができているかどうかを示します。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["インスタンス管理"]



=== 生成AIワークロード



==== 運用の監視と追跡に使用可能なトラッカー

GenAIでTracker監視機能が利用可能になりました。Trackerを使用すると、保留中、進行中、完了済みの操作の進行状況とステータスを監視および追跡したり、操作タスクとサブタスクの詳細を確認したり、問題や失敗を診断したり、失敗した操作のパラメータを編集したり、失敗した操作を再試行したりできます。

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["BlueXP ワークロード ファクトリーの Tracker を使用してワークロード操作を監視する"]



==== 知識ベースの再ランク付けモデルを選択する

ナレッジベースで使用する特定のリランカーモデルを選択することで、再ランク付けされたクエリ結果の関連性を高めることができます。GenAIは、Cohere RerankモデルとAmazon Rerankモデルをサポートしています。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



== 2025年5月04日



=== データベースワークロード



==== ダッシュボードの機能拡張

* BlueXP  ワークロードファクトリコンソールのタブ間を移動すると、アカウント間ビューとリージョン間ビューを使用できます。新しいビューは、リソースの管理、監視、最適化を改善します。
* ダッシュボードの* Potential Savings *タイルから、Amazon Elastic Block StoreまたはAmazon FSx for WindowsファイルサーバからFSx for ONTAPに切り替えることで、削減可能なコストをすばやく確認できます。




==== データベース構成で使用可能なアドホックスキャン

BlueXP  Workload Factory for Databasesは、管理対象のMicrosoft SQL ServerインスタンスをFSx for ONTAPストレージで自動的にスキャンし、潜在的な構成の問題がないかどうかを確認します。毎日のスキャンに加えて、いつでもスキャンできます。



==== オンプレミス評価記録の削除

オンプレミスのMicrosoft SQL Serverホストの削減効果を確認したら、オンプレミスのホストレコードをBlueXP  ワークロードファクトリから削除することもできます。



==== 最適化の機能拡張



===== クローンのクリーンアップ

クローンクリーンアップの評価と修正では、コストのかかる古いクローンを特定して管理します。60日を経過したクローンは、BlueXP  ワークロードファクトリコンソールで更新または削除できます。



===== 構成分析の延期と却下

一部の設定はデータベース環境に適用されない場合があります。特定の構成分析を30日延期するか、分析を却下するかを選択できるようになりました。



==== オンプレミス評価記録の削除

オンプレミスのMicrosoft SQL Serverホストの削減効果を確認したら、オンプレミスのホストレコードをBlueXP  ワークロードファクトリから削除することもできます。



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* NetAppデータインフラのインサイトをデータソースとして*：ワークロードファクトリは、EC2移行アドバイザのデータコレクタを使用すると、NetAppデータインフラのインサイトに直接接続して、VMwareの導入情報を収集できるようになりました。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== 生成AIワークロード



==== Amazon Q Business 向け NetApp コネクタのサポート

GenAI のこのリリースでは、NetApp Connector for Amazon Q Business のサポートが導入され、Amazon Q Business 用のコネクタを作成できるようになりました。Amazon Bedrock用の 生成AIナレッジベースを構築するよりも、初期設定が少なくて済み、Amazon Q Business AIアシスタントをすばやく簡単に活用できます。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Amazon Q Business 用の NetApp コネクタを作成する"]



==== 強化されたチャットモデルサポート

生成AIでは、ナレッジベース用に次の追加チャットモデルがサポートされるようになりました。

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AIモデル"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titanテキストモデル"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llamaモデル"^]
* link:https://docs.ai21.com/["Jamba 1.5モデル"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohereコマンドモデル"^]
* link:https://aws.amazon.com/bedrock/deepseek/["ディープシークモデル"^]


生成AIは、Amazon Bedrockがサポートする各プロバイダのモデルをサポートしています。link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon Bedrockでサポートされる基盤モデル"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== セットアップと管理



==== CloudShellオートコンプリートのサポート

BlueXP  ワークロードファクトリCloudShellを使用している場合は、コマンドの入力を開始してTabキーを押すと、使用可能なオプションが表示されます。複数の候補が存在する場合は、CLIに候補のリストが表示されます。この機能は、エラーを最小限に抑え、コマンド実行を高速化することで、生産性を向上させます。



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== ビルダーのワークロード



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



== 2025年3月30日



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* *ボリューム割り当てガイダンスの強化*：EC2 Migration Advisorの「Classify」および「Package」ステップのボリューム割り当て情報には、読みやすさと操作性が向上しています。各ボリュームについて、より有益な情報が表示されるため、ボリュームの特定や割り当て方法の決定に役立ちます。
* *データコレクタスクリプトの効率化*: EC2移行アドバイザのデータコレクタスクリプトは、小規模なVM環境でデータを収集する際のCPU使用率を最適化します。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



=== セットアップと管理



==== ONTAP CLIコマンドについて、AIによって生成されたエラー応答がCloudShellで報告される

CloudShellを使用している場合、ONTAP CLIコマンドを発行してエラーが発生するたびに、失敗の説明、失敗の原因、詳細な解決策を含むAI生成のエラー応答を取得できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用"]



==== IAM：SimulatePermissionPolicy権限の更新

AWSアカウントのクレデンシャルを追加したり、生成AIワークロードなどの新しいワークロード機能を追加したりするときに、ワークロードファクトリコンソールから権限を管理できるようになりまし `iam:SimulatePrincipalPolicy`た。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]



== 2024年12月01日



=== ビルダーのワークロード



==== ビルダーワークロードの初回リリース

BlueXP  Workload Factory for Buildersは、ソフトウェアバージョンの消費とアクセスを簡素化し、カスタムツールやスクリプトの必要性を排除します。ソフトウェアバージョンをPerforce Helix Coreと統合されたインスタントクローンとして使用し、開発プロセスに便利なワークスペースとして使用できるため、時間とリソースを節約できます。

初期リリースには、プロジェクトとワークスペースを管理し、Codeboxを使用してアクションを自動化する機能が含まれています。また、BuildersとPerforce Helix Coreを統合することで、プロジェクトごとに異なるバージョンを管理し、すばやく切り替えることができます。
