---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: NetApp Workload Factory の一部であるワークロードの最新の変更について説明します。 
---
= NetApp Workload Factoryの最近の変更点
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory の一部であるワークロードの最新の変更について説明します。



== 2026年1月4日



=== データベースワークロード



==== Ask me AIアシスタントのホームページ統合

Workload Factory コンソールのホームページには Ask me AI アシスタントが組み込まれており、独自のストレージ資産について質問したり、環境から直接パーソナライズされた分析情報を取得したり、以前の会話を参照したりすることができます。コンソールを離れることなく、「Ask me」と対話してワークロードを理解し、問題をトラブルシューティングし、Workload Factory について詳しく知ることができます。



=== VMwareワークロード



==== Ask me AIアシスタントのホームページ統合

Workload Factory コンソールのホームページには Ask me AI アシスタントが組み込まれており、独自のストレージ資産について質問したり、環境から直接パーソナライズされた分析情報を取得したり、以前の会話を参照したりすることができます。コンソールを離れることなく、「Ask me」と対話してワークロードを理解し、問題をトラブルシューティングし、Workload Factory について詳しく知ることができます。



== 2025年12月18日



=== データベースワークロード



==== Active Directory統合の強化

Workload Factory for Databases には、*詳細作成* オプションを使用して Microsoft SQL Server を展開するときに、3 つの新しい Active Directory (AD) フィールドが含まれます。これらの機能強化により、Active Directory 参加の設定を指定し、管理されたサービス アカウントを使用できるようになります。

新しい AD フィールドは次のとおりです。

* 優先ドメインコントローラ
* 優先組織単位パス
* 対象の Active Directory グループ


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Microsoft SQL Server を導入する"]



== 2025年12月4日



=== NetApp ONTAP 対応の Amazon FSX



==== FSx for ONTAPの AWS S3 アクセス ポイントのサポート

NetApp Workload Factory は、 FSx for ONTAPファイルシステム用の AWS S3 アクセスポイントをサポートしています。S3 アクセス ポイントを使用してボリュームを作成し、既存のボリュームに S3 アクセス ポイントを割り当て、Workload Factory コンソールから S3 アクセス ポイントを管理できます。S3 アクセスポイントを使用すると、AWS S3 API を介して SMB/CIFS または NFS ボリューム上にあるファイルデータにアクセスできます。これにより、既存のデータを、S3 アクセスポイントをサポートする AWS サービスの GenAI、ML、分析と統合できます。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["S3 アクセスポイントを使用してボリュームを作成する"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["ボリュームのS3アクセスポイントを管理する"]




== 2025年11月27日



=== NetApp ONTAP 対応の Amazon FSX



==== NetApp Workload Factoryにおけるブロックデバイスのサポート

NetApp Workload Factoryで新しく導入されたブロック デバイス サポートを使用して、ブロック デバイスをより効率的に管理します。この機能を使用すると、iSCSI LUN の詳細を表示して容量を増やすことができるため、ストレージ ニーズに合わせて柔軟性が向上します。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Workload Factoryでブロックデバイスを管理する"]



==== Well-Architected 分析の更新

ワークロード ファクトリーは、次の構成について FSx for ONTAPファイル システムを分析します。

* 不要なスナップショットの削除: ボリュームに、コストを削減するために削除できる古い不要なスナップショットがあるかどうかを確認します。
* FlexGroupボリュームの再バランス: FlexGroupボリュームがメンバー ボリューム間で均等にバランス調整され、最適なパフォーマンスが確保されているかどうかを確認します。


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["FSx for ONTAPファイルシステムの Well-Architected ステータスを表示します"]



==== NetApp Workload Factoryの EMS イベント用 AI アナライザー

NetApp Workload Factory は、 ONTAPイベント管理システム (EMS) イベント用の AI 搭載アナライザーを導入しました。この機能は、EMS イベント データの分析に基づいて洞察と推奨事項を提供することで、問題を迅速に特定してトラブルシューティングするのに役立ちます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Workload Factory で EMS イベントを分析する"]



==== FSx for ONTAPファイルシステムのコストと使用状況の傾向を監視する

NetApp Workload Factoryコンソールから直接、FSx for ONTAPファイルシステムのコストと使用状況の傾向を監視できます。この機能は、ストレージの消費量とコストのメトリック、および明細化されたコストを提供し、リソースの割り当てと予算計画の最適化に役立ちます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Workload Factory で FSx for ONTAPファイルシステムのコストを追跡する"]



==== NetApp Workload Factoryでファイルシステムの FSx タグを管理する

NetApp Workload Factoryコンソールからファイルシステムの FSx タグを直接簡単に管理できます。この機能を使用すると、タグを追加、編集、または削除できるため、FSx for ONTAPファイルシステムの整理と分類を効率化できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Workload Factory で FSx タグを管理する"]



==== FSx for ONTAPファイルシステムのキャッシュ容量を調整する

Workload Factory コンソールからキャッシュ ボリュームの容量を増減できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Workload Factory でキャッシュボリュームを管理する"]



=== データベースワークロード



==== Amazon Elastic Block Store (EBS) のデータベース計算ツールで節約を最適化

2 つの新しい計算機能により、EBS ストレージを使用して複数のインスタンスを実行する際のコスト削減分析が改善され、FSx for ONTAPに切り替えることでさらにコストを削減できるようになります。

* Workload Factory は、1 つの FSx for ONTAPファイル システム上の複数のデータベース ホストに統合されたストレージ ソリューションを提供します。この統合により、複数のデータベース ホストに必要なファイル システムの数が削減され、ストレージ コストが最適化され、コスト削減が向上します。
* Workload Factory は、EBS パフォーマンスの使用状況を分析し、最適かつ最もコスト効率の高い FSx for ONTAP構成を提案します。


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["検出されたEBSホストの節約を調べる"]



==== Well-Architected ダッシュボードで利用可能な Excel レポート

適切に設計されたダッシュボードの Excel レポートをダウンロードできます。このレポートには、データベース リソースの well-architeccted ステータスと、オペレーティング システムおよびONTAPのサブ構成を含むすべてのリソース構成の推奨事項が示されます。



==== Oracle データベースで利用可能なエラー ログ アナライザー

Agentic AI 搭載のエラー ログ アナライザーは、Oracle データベースで使用できます。この機能は、高度な機械学習アルゴリズムを活用して、ログ ファイル内のエラーを自動的に検出して分析します。このツールは、ログで識別されたパターンに基づいて開発者に実用的な洞察と推奨事項を提供することで、トラブルシューティング プロセスを合理化することを目的としています。

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Agentic AI搭載エラーログアナライザーの詳細"]



==== Oracle 向けの Well-Architected 分析

Well-Architected 分析には、2 つの新しいストレージ サイズ設定構成が含まれています。この分析では、既存の Oracle データベース デプロイメントのスワップ領域の割り当てとファイル システムのヘッドルームに関連する構成の問題を評価および修正します。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Workload Factory で Well-Architected データベース構成を実装する"]



=== VMwareワークロード



==== 特定のリージョンにおける Amazon Elastic VMware Service への移行によるコスト削減を計算します

クラウド移行のためのさまざまな展開オプションの価値を調査し、ソリューション評価に投入された労力を最適化し、クラウドで価値と節約をもたらす可能性のあるソリューションを詳細に調査できるようになりました。

また、EVS 展開で FSx for ONTAPを使用することで実現できる vCPU コアの節約を確認することもできます。

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["NetApp Workload Factoryで Amazon Elastic VMware Service の割引価格をご確認ください"]



=== セットアップと管理



==== ストレージの権限の更新

FSx for ONTAP EMS イベント アナライザーは、_operations and remediation_ 権限ポリシーの次の Amazon Bedrock 権限を使用して、ストレージ ワークロードのイベント データを取得します。

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["権限参照の変更ログ"]



== 2025年11月2日



=== NetApp ONTAP 対応の Amazon FSX



==== キャッシュボリューム管理

Workload Factory コンソール内から、次のキャッシュ ボリューム管理操作を実行できます。

* キャッシュ名を編集する
* キャッシュボリュームの容量を増やす
* キャッシュボリュームのマウントパスまたはエクスポートポリシーを編集する
* キャッシュボリュームのキャッシュ方法（モード）を変更する
* キャッシュボリュームを事前設定する
* キャッシュボリュームを削除する


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["キャッシュボリュームを管理する"]



==== 自動inode管理が利用可能

自動容量管理を有効にする必要なく、自動 inode 管理を有効にすることができます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["自動inode管理を有効にする"]



==== 容量とinode使用量のしきい値警告設定

しきい値警告は、容量と inode 使用量の両方に対して利用できます。自動容量または inode 管理を有効にするときに、これらのしきい値を設定できます。この設定を使用するには、link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory通知サービス"^] 。



==== ボリュームサイズの縮小が可能

NetApp Workload Factoryで NFS および SMB/CIFS ボリュームのサイズを縮小できます。この機能により、現在の容量では不要になったボリュームのサイズを縮小できるため、ストレージ リソースをより適切に管理できるようになります。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["ボリュームの容量を減らす"]



==== 強化された FSx for ONTAPリソース状態

Workload Factory では、「構成ミス」のリソース状態が拡張され、リソースの実際の問題の説明が含まれるようになりました。



==== Well-Architected 分析の更新

ワークロード ファクトリーは、次の構成について FSx for ONTAPファイル システムを分析します。

* ボリューム使用率がほぼ満杯: ファイル容量の 80% 以上を使用しているボリュームがあるかどうかを確認します。これにより、追加の容量が必要なボリュームを特定できます。
* ボリュームへの不正アクセス: NFS または SMB/CIFS マウント パスを使用して iSCSI ボリュームにアクセスできるかどうかを確認し、ボリュームへの不正アクセスを削除してセキュリティ リスクを回避できます。




==== Workload Factory for Storage の権限の変更

Workload Factory では、特定のアクションに必要な権限がより明確に示され、必要な権限のみを細かく選択できます。資格情報を追加すると、以前の権限モデルである _読み取り専用_ と _読み取り/書き込み_ の代わりに、3 つの権限オプションから選択できるようになります。新しい権限モデルでは、権限ポリシーが次のように分割されます。

* _表示、計画、分析_: FSx for ONTAPファイル システムを表示し、システムの健全性を把握し、システムの Well-Architected 分析を取得して、コスト削減を検討します。
* _操作と修復_: ファイル システム容量の調整やファイル システム構成の問題の修正などの運用タスクを実行します。
* _ファイルシステムの作成と削除_: FSx for ONTAPファイルシステムとストレージ VM を作成および削除します。


資格情報を追加するときに、Workload Factory に提供するアクセス レベルに基づいて、これらのアクセス許可ポリシーを 1 つ以上選択できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["ワークロードファクトリーの権限リファレンス"]



==== FSx for ONTAPサイバー ボールト サポート

サイバー ボールト アーキテクチャで、FSx for ONTAP をソースまたはターゲットとして使用してサイバー ボールトを作成できます。サイバー ボールトは、重要なデータを保存するための安全で隔離された環境を提供し、ランサムウェアやその他のサイバー脅威からデータを保護します。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["FSx for ONTAPでサイバー ボールトをセットアップする"]



=== データベースワークロード



==== ダッシュボードの改善

新しいダッシュボードは合理化され、整理され、データベース リソースと Workload Factory の主要機能の概要を 1 つの画面でより明確に表示します。1 枚のカードではデータベース リソースが強調表示され、1 枚のカードでは Well-Architected スコアと分析に関する情報が提供され、1 枚のカードではエラー分析が表示され、2 枚のカードでは月間コストと潜在的な節約額が表示され、1 枚のカードではサンドボックスに関する情報が表示されます。



==== Oracle 向けの Well-Architected 分析

Well-Architected 分析には、Oracle 構成に対する次の評価と修正が含まれます。

* NFS プロトコルを使用したストレージ構成オペレーティング システム: 既存の Oracle データベース デプロイメントの NFS 構成に関する構成の問題を評価および修正します。
* iSCSI プロトコルを使用したストレージ構成オペレーティング システム: 既存の Oracle データベース デプロイメントの iSCSI 構成に関する構成問題を評価して修正します。
* Automatic Storage Management (ASM) を使用したストレージ構成オペレーティング システム: 既存の Oracle データベース展開の ASM 構成に関する構成の問題を評価します。


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Workload Factory で Well-Architected データベース構成を実装する"]



==== Workload Factory for Databases の権限の変更

Workload Factory for Databases では、権限ポリシーが更新され、特定のアクションに必要な内容がより明確になり、必要な権限のみを選択するための細分性が高まりました。資格情報を追加すると、以前の権限モデルである _読み取り専用_ と _読み取り/書き込み_ の代わりに、3 つの権限オプションから選択できるようになります。新しい権限モデルでは、権限ポリシーが次のように分割されます。

* _表示、計画、分析_: データベース リソースのインベントリを表示し、リソースの健全性を把握し、データベース構成の Well-Architected 分析を確認し、エラー ログ分析を取得し、節約を検討します。
* _運用と修復_: データベース リソースの運用タスクを実行し、データベース構成と基盤となる FSx for ONTAPファイル システム ストレージの問題を修正します。
* _データベース ホストの作成_: ベスト プラクティスに従って、データベース ホストと、その基盤となる FSx for ONTAPファイル システム ストレージを展開します。


資格情報を追加するときに、Workload Factory for Databases に提供するアクセス レベルに基づいて、これらのアクセス許可ポリシーを 1 つ以上選択できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["ワークロードファクトリーの権限リファレンス"^]



==== よく設計されたダッシュボード画面が追加されました

新しい _Well-architected_ ダッシュボード画面がデータベース メニューに追加されました。この画面から、データベース資産全体の構成ステータスの集約ビューを取得できます。



==== NetApp Backup and Recoveryにおけるデータベース導入時の編集保護

Workload Factory コンソールから、保護されたリソースの保護を編集することを選択すると、 NetApp Consoleのバックアップとリカバリにリダイレクトされ、保護ポリシーまたはスケジュールを変更できます。

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["データベースデプロイメントの編集保護"]



==== エラー分析機能で利用可能なタグによるエラーフィルタリング

Workload Factory のエラー分析機能を使用すると、インフラストラクチャ指向のタグで Microsoft SQL Server エラー ログをフィルター処理して表示できます。この機能強化により、問題を迅速にトリアージ、トラブルシューティング、解決できるようになります。

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["タグフィルタリングでエラーログを分析する"^]



=== VMwareワークロード



==== FSx for ONTAPファイルシステムのデプロイメントウィザードに Amazon Elastic VMware Service の設定を導入

Amazon Elastic VMware Service の外部 NFS データストアとして使用する FSx for ONTAPファイル システムをデプロイするときに、データストアが接続される EVS 環境を選択できるようになりました。これにより、デプロイメント ウィザードのいくつかのフィールドが自動的に入力され、デプロイメント プロセスが簡素化されます。

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["推奨される FSx for ONTAPファイルシステムを導入する"]



==== VMware ワークロードの権限の変更

VMware ワークロードでは、特定のアクションに必要な権限がより明確に示され、必要な権限のみを詳細に選択できます。資格情報を追加すると、以前の権限モデルである _読み取り専用_ と _読み取り/書き込み_ の代わりに、2 つの権限オプションから選択できるようになります。新しい権限モデルでは、権限ポリシーが次のように分割されます。

* _表示、計画、および分析_: EVS 仮想化環境のインベントリを表示し、システムの Well-Architected 分析を取得して、コスト削減を検討します。
* _データストアのデプロイと接続_: 推奨される VM レイアウトを Amazon EVS、Amazon EC2、または VMware Cloud on AWS vSphere クラスターにデプロイし、カスタマイズされたAmazon FSx for NetApp ONTAPファイルシステムを外部データストアとして使用します。


資格情報を追加するときに、VMware ワークロードに提供するアクセス レベルに基づいて、これらの権限ポリシーを 1 つ以上選択できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["ワークロードファクトリーの権限リファレンス"^]



==== Amazon EC2 移行アドバイザーの改善

NetApp Workload Factory for VMware のこのリリースでは、移行アドバイザーのエクスペリエンスがいくつか改善されています。

* *移行計画の保存またはダウンロード*: 移行計画を PDF または CSV ファイルとして保存またはダウンロードできるようになりました。移行計画を保存すると、その計画は Workload Factory アカウントに保存されます。




=== セットアップと管理



==== 権限の更新

このリリースでは、セキュリティとユーザー制御を強化するために、ストレージ、データベース、VMware ワークロードの権限ポリシーに大幅な更新を加えました。権限設定をより細かくカスタマイズして、必要に応じて権限を追加または解除できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory の権限リファレンス"]



==== ストレージの新しい通知

NetApp Workload Factory通知サービスには、ストレージの自動 inode 管理に関する通知が含まれています。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factory の通知"]



==== 自動容量および inode 管理のしきい値警告

ストレージの自動容量および inode 管理は、Workload Factory 通知サービスからの通知をトリガーする警告しきい値を使用して設定できます。この機能を使用するには、まず Workload Factory 通知サービスを有効にする必要があります。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["NetApp Workload Factoryの通知を構成する"]
