---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: BlueXP  ワークロードファクトリに含まれているワークロードに対する最新の変更について説明します。 
---
= BlueXP  ワークロードファクトリにおける最近の変更
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
BlueXP  ワークロードファクトリに含まれているワークロードに対する最新の変更について説明します。



== 2025年6月08日



=== NetApp ONTAP 対応の Amazon FSX



==== 問題解決のための新しい優れた分析とサポート

FSx for ONTAP ファイルシステムの自動容量管理が、Well-Architected ステータス ダッシュボードの構成分析として含まれるようになりました。

さらに、ワークロード ファクトリーでは、次の構成の問題の修正がサポートされるようになりました。

* SSD容量しきい値
* データの階層化
* スケジュールされたローカルSnapshot
* FSx for ONTAP バックアップ
* リモートデータレプリケーション
* ストレージの効率化
* 自動容量管理


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["構成の問題を修正する"]



== 2025年6月03日



=== NetApp ONTAP 対応の Amazon FSX



==== ボリューム自動拡張の強化

ビジネス ニーズやアプリケーション要件に応じて、ボリューム サイズがプロビジョニングされたサイズを超えて拡張できるように、ボリュームの自動拡張サイズを設定できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["ボリュームの自動拡張を有効にする"]



==== Well-Architected 分析のアップデート

Workload Factory は、FSx for ONTAP ファイルシステムを分析し、データコンパクション、圧縮、重複排除といったストレージ効率が活用されているかどうかを確認します。ストレージ効率は、ファイルシステムが利用可能なスペースをどれだけ効率的に使用しているかを測定します。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ストレージ効率の適切なアーキテクチャの状態を表示する"]



==== ストレージダッシュボードの機能強化

本日より、ワークロードファクトリーコンソールからストレージワークロードを開くと、*ダッシュボード*が表示されます。新しく設計されたダッシュボードでは、ファイルシステムの数、SSDの総容量、Well-Architectedステータスの概要、データ保護の概要、レプリケーション関係の健全性など、FSx for ONTAPシステムの包括的なビューを提供します。



==== ボリュームタブの機能強化

ストレージワークロードでは、ワークロードファクトリーコンソールのFSx for ONTAPファイルシステム内の「ボリューム」タブが強化されました。強化された内容は次のとおりです。

* *新しいカード*: SSD 容量、容量プール、自律ランサムウェア保護 (ARP)
* *新しい列*: 容量分布、使用済み SSD 容量、使用済み容量プール、SSD 効率




==== ボリューム作成時のストレージ効率のアップデート

新しいボリュームを作成すると、データの圧縮、圧縮、重複排除などのストレージ効率がデフォルトで有効になります。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["ワークロードファクトリーに新しいボリュームを作成する"]



=== データベースワークロード



==== PostgreSQLとOracleの検出

ワークロードファクトリーコンソール内で、AWSアカウントでPostgreSQLサーバーデータベースとOracleデータベースデプロイメントを実行しているインスタンスを検出できるようになりました。検出されたインスタンスはデータベースインベントリに表示されます。



==== 「最適化」の用語を更新しました

以前は「最適化」と呼ばれていたワークロード ファクトリーでは、現在、「well-architected の問題」と「well-architected ステータス」を使用してデータベース構成の分析を説明し、「修正」を使用してベスト プラクティスの推奨事項を満たすようにデータベース構成を改善する機会の修復を説明します。

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["ワークロードファクトリーにおけるデータベース環境の構成分析"]



==== ホストインスタンスのオンボーディングの改善

ホストインスタンスの管理において、「未検出」「管理対象外」「管理対象」といった用語が使用されていたのに対し、ワークロードファクトリーではホストインスタンスのオンボーディングに「登録」という用語を使用するようになりました。新しい登録プロセスには、ホストインスタンスの認証と準備が含まれており、ワークロードファクトリーコンソール内でデータベース構成のリソースを作成、監視、分析、修正できるようになります。登録プロセスの準備手順は、ホストインスタンスが管理の準備ができているかどうかを示します。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["インスタンス管理"]



=== 生成AIワークロード



==== 運用の監視と追跡に使用可能なトラッカー

GenAIでTracker監視機能が利用可能になりました。Trackerを使用すると、保留中、進行中、完了済みの操作の進行状況とステータスを監視および追跡したり、操作タスクとサブタスクの詳細を確認したり、問題や失敗を診断したり、失敗した操作のパラメータを編集したり、失敗した操作を再試行したりできます。

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["BlueXP ワークロード ファクトリーの Tracker を使用してワークロード操作を監視する"]



==== 知識ベースの再ランク付けモデルを選択する

ナレッジベースで使用する特定のリランカーモデルを選択することで、再ランク付けされたクエリ結果の関連性を高めることができます。GenAIは、Cohere RerankモデルとAmazon Rerankモデルをサポートしています。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



== 2025年5月04日



=== NetApp ONTAP 対応の Amazon FSX



==== FSx for ONTAPファイルシステム向け自律型ランサムウェア対策

自律型ランサムウェア対策（ARP）でデータを保護：NAS（NFS / SMB）環境でワークロードを分析し、ランサムウェア攻撃の可能性がある異常なアクティビティを検出して警告する機能です。攻撃が疑われると、ARPは変更不可能な新しいスナップショットも作成し、そこからデータを復元できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["自律型ランサムウェア対策でデータを保護"]



==== FlexGroupボリュームのリバランシングの強化

BlueXP  ワークロード工場出荷時に導入されたFlexGroupボリュームリバランシングウィザードには、FlexGroupボリューム内のデータをリバランシングするためのいくつかのレイアウトオプションが用意されています。リバランシングを実行すると、FlexGroupメンバーボリュームにデータが均等に再配分されます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["FlexGroupボリューム内の容量のリバランシング"]



==== FSx for ONTAPファイルシステムのベストプラクティスを実装

BlueXP  ワークロードファクトリには、ファイルシステム構成の適切な設計ステータスを確認できるダッシュボードが用意されています。この分析を活用して、FSx for ONTAPファイルシステムのベストプラクティスを実装できます。ファイルシステム構成の分析には、SSD容量のしきい値、スケジュールされたローカルスナップショット、FSx for ONTAPのスケジュールされたバックアップ、データ階層化、リモートデータレプリケーションなどの構成が含まれます。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["ファイルシステム構成の適切に設計された分析をご紹介します"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["ファイルシステムのベストプラクティスの実装"]




==== デュアルプロトコルボリュームのセキュリティ形式のオプション

ボリュームのセキュリティ形式としてNTFSまたはUNIXを選択して、ユーザや権限がボリュームにアクセスする方法を決定できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["ボリュームの作成"]



==== レプリケーションの機能拡張



===== FSx for ONTAPからオンプレミスへのリバースレプリケーションをサポート

FSx for ONTAPファイルシステムからオンプレミスのONTAPクラスタへのリバースレプリケーションを、ワークロードファクトリコンソールから利用できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["リバースレプリケーション"]



===== データ保護ボリュームのレプリケーション

データ保護ボリュームをレプリケートできるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["データ保護ボリュームをレプリケートする"]



===== 複数ボリュームの選択

複数のボリュームを選択できるため、レプリケートするボリュームを正確に選択できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["レプリケーション関係を作成する"]



===== 長期保持ポリシーのラベル

レプリケーション関係に対して長期保持を有効にする場合は、ソースボリュームとターゲットボリュームのラベルが完全に一致している必要があります。BlueXP  ワークロードファクトリで、欠落しているソースボリュームラベルが自動的に作成されるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["レプリケーション関係を作成する"]



==== FSx for ONTAPのファイル名がボリューム作成時に表示される

FSx for ONTAPファイルシステムのボリューム作成時の可視性が向上しました。ボリュームを作成するとFSx for ONTAPファイルシステムが表示されるため、ボリュームが作成されている場所を正確に把握できます。



==== ストレージワークロード全体でAWSアカウントを認識

ストレージワークロード全体のアカウントの可視性が向上しました。AWSアカウントは、*[ボリューム]*、*[Storage VM]*、*[レプリケーション]*の各タブに移動すると表示されます。



==== リンクアソシエーションの機能拡張

* FSx for ONTAPファイルシステムからのリンクは、[インベントリ]タブで簡単に関連付けることができます。
* BlueXP  ワークロードファクトリでは、リンクの関連付けに代替ONTAPユーザクレデンシャルの使用がサポートされるようになりました。




==== AWS Secrets Managerのリンク認証のサポート

AWS Secrets Managerのシークレットを使用してリンクを認証できるようになり、BlueXP  ワークロードファクトリに保存されているクレデンシャルを使用する必要がなくなりました。



==== トラッカー応答サポート

TrackerでAPI応答が返されるようになり、タスクに関連するREST API出力を確認できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Trackerを使用した操作の監視"]



==== バックアップからボリュームをリストアする際の容量の検証

バックアップからボリュームをリストアする場合、BlueXP  ワークロードの工場出荷時にリストアに十分な容量があるかどうかが確認され、十分でない場合はSSDストレージ階層の容量が自動的に追加されます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["バックアップからボリュームをリストアする"]



==== 代替ONTAPユーザクレデンシャルのサポート

Workload Factoryでは、ファイルシステムを作成するためのONTAPクレデンシャルの代替セットがサポートされるようになりました。fsxadminユーザだけを使用する代わりに、別のONTAPクレデンシャルのセットを選択するか、fsxadminユーザとvsaadminユーザのパスワードを指定しないように選択できます。



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== データベースワークロード



==== ダッシュボードの機能拡張

* BlueXP  ワークロードファクトリコンソールのタブ間を移動すると、アカウント間ビューとリージョン間ビューを使用できます。新しいビューは、リソースの管理、監視、最適化を改善します。
* ダッシュボードの* Potential Savings *タイルから、Amazon Elastic Block StoreまたはAmazon FSx for WindowsファイルサーバからFSx for ONTAPに切り替えることで、削減可能なコストをすばやく確認できます。




==== データベース構成で使用可能なアドホックスキャン

BlueXP  Workload Factory for Databasesは、管理対象のMicrosoft SQL ServerインスタンスをFSx for ONTAPストレージで自動的にスキャンし、潜在的な構成の問題がないかどうかを確認します。毎日のスキャンに加えて、いつでもスキャンできます。



==== オンプレミス評価記録の削除

オンプレミスのMicrosoft SQL Serverホストの削減効果を確認したら、オンプレミスのホストレコードをBlueXP  ワークロードファクトリから削除することもできます。



==== 最適化の機能拡張



===== クローンのクリーンアップ

クローンクリーンアップの評価と修正では、コストのかかる古いクローンを特定して管理します。60日を経過したクローンは、BlueXP  ワークロードファクトリコンソールで更新または削除できます。



===== 構成分析の延期と却下

一部の設定はデータベース環境に適用されない場合があります。特定の構成分析を30日延期するか、分析を却下するかを選択できるようになりました。



==== オンプレミス評価記録の削除

オンプレミスのMicrosoft SQL Serverホストの削減効果を確認したら、オンプレミスのホストレコードをBlueXP  ワークロードファクトリから削除することもできます。



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* NetAppデータインフラのインサイトをデータソースとして*：ワークロードファクトリは、EC2移行アドバイザのデータコレクタを使用すると、NetAppデータインフラのインサイトに直接接続して、VMwareの導入情報を収集できるようになりました。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== 生成AIワークロード



==== Amazon Q Business 向け NetApp コネクタのサポート

GenAI のこのリリースでは、NetApp Connector for Amazon Q Business のサポートが導入され、Amazon Q Business 用のコネクタを作成できるようになりました。Amazon Bedrock用の 生成AIナレッジベースを構築するよりも、初期設定が少なくて済み、Amazon Q Business AIアシスタントをすばやく簡単に活用できます。

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Amazon Q Business 用の NetApp コネクタを作成する"]



==== 強化されたチャットモデルサポート

生成AIでは、ナレッジベース用に次の追加チャットモデルがサポートされるようになりました。

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Mistral AIモデル"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Amazon Titanテキストモデル"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Meta Llamaモデル"^]
* link:https://docs.ai21.com/["Jamba 1.5モデル"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Cohereコマンドモデル"^]
* link:https://aws.amazon.com/bedrock/deepseek/["ディープシークモデル"^]


生成AIは、Amazon Bedrockがサポートする各プロバイダのモデルをサポートしています。link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Amazon Bedrockでサポートされる基盤モデル"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



=== セットアップと管理



==== CloudShellオートコンプリートのサポート

BlueXP  ワークロードファクトリCloudShellを使用している場合は、コマンドの入力を開始してTabキーを押すと、使用可能なオプションが表示されます。複数の候補が存在する場合は、CLIに候補のリストが表示されます。この機能は、エラーを最小限に抑え、コマンド実行を高速化することで、生産性を向上させます。



==== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。

<stdin> 内の未解決のディレクティブ - include::_include/workload-builders.adoc[] :leveloffset: +1



=== 権限に関する用語を更新

ワークロード ファクトリのユーザー インターフェースとドキュメントでは、読み取り権限を示すために「読み取り専用」を使用し、自動化権限を示すために「読み取り/書き込み」を使用するようになりました。



== 2025年4月04日



=== データベースワークロード



==== 最適化の機能拡張

データベース環境を最適化する際に、新しい最適化評価、修正、複数のリソースの表示を利用できます。



===== 耐障害性の評価

強化された機能には、データベース環境に対してデータの冗長性とディザスタリカバリ機能が設定されているかどうかをチェックするための新しい耐障害性評価が含まれています。

* FSx for ONTAPバックアップ：SQL Serverインスタンスのボリュームを提供するFSx for ONTAPファイルシステムが、定期的なFSx for ONTAPバックアップで設定されているかどうかを分析します。
* リージョン間レプリケーション：Microsoft SQL Serverインスタンスを提供するFSx for ONTAPファイルシステムでリージョン間レプリケーションが設定されているかどうかを評価します。




===== コンピューティングの修正

受信側スケーリング（RSS）修正は、ネットワーク処理を複数のプロセッサに分散し、効率的な負荷分散を確保するようにRSSを構成します。



===== ローカルSnapshotの修正

ローカルSnapshotの修正では、データ損失が発生した場合にデータベース環境の耐障害性を維持するために、Microsoft SQL ServerインスタンスのボリュームのSnapshotポリシーを設定します。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



===== 複数リソース選択のサポート

データベース設定を最適化する際に、すべてのリソースではなく特定のリソースを選択できるようになりました。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



==== インベントリビューの改善

ワークロードファクトリコンソールの[Inventory]タブは合理化され、Amazon FSx for NetApp ONTAPで実行されるSQLサーバのみが含まれるようになりました。SQLサーバーはオンプレミスで、Amazon Elastic Block StoreとAmazon FSx for Windows File Serverで稼働しています。



==== PostgreSQLサーバー展開で利用可能なクイック作成

この迅速な導入オプションを使用すると、HA構成とベストプラクティスが組み込まれたPostgreSQLサーバを作成できます。

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["BlueXP  ワークロードファクトリでPostgreSQLサーバを作成する"]



== 2025年3月30日



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* *ボリューム割り当てガイダンスの強化*：EC2 Migration Advisorの「Classify」および「Package」ステップのボリューム割り当て情報には、読みやすさと操作性が向上しています。各ボリュームについて、より有益な情報が表示されるため、ボリュームの特定や割り当て方法の決定に役立ちます。
* *データコレクタスクリプトの効率化*: EC2移行アドバイザのデータコレクタスクリプトは、小規模なVM環境でデータを収集する際のCPU使用率を最適化します。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



=== 生成AIワークロード



==== ファイル形式のサポートの強化

このリリースの 生成AIでは、データソースからファイルを取り込む際のJSONおよびJSONPファイル形式のサポートが導入されて `.json`います。ネストされたオブジェクトを含むJSONファイルがサポートされますが、ネストされた配列はサポートされません。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["サポートされるデータソースファイル形式"]



==== 外部チャットボットサンプルアプリケーションの国際化サポート

生成AIサンプル外部チャットボットアプリケーションのユーザーインターフェイスを別の言語やロケールに簡単に変更できるようになりました。

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["生成AI外部サンプルチャットボットアプリケーション"]



==== Anthropic Claude Sonnet 3.7チャットモデルのサポート

生成AIでは、Anthropic Claude 3.7 Sonnetチャットモデルがサポートされるようになりました。Claude 3.7 Sonnetのベータ機能は、要求ごとに最大128Kの出力トークンを可能にし、新しいコンピュータの使用アクションをサポートします。Claude 3.7 Sonnet拡張思考モードは、将来の 生成AIリリースでサポートされる予定です。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



==== 汎用NFS / SMB共有からのデータソースの追加のサポート

ワークロードファクトリAPIを使用して、一般的なNFSv3、NFSv4、またはSMB共有からデータソースを追加できるようになりました。NFS共有またはSMB共有からデータソースを追加しても、ナレッジベースボリュームはAmazon FSx for NetApp ONTAPボリュームに残ります。この機能は、ワークロードファクトリのWeb UIで今後のリリースでサポートされる予定です。

link:https://console.workloads.netapp.com/api-doc["ワークロードファクトリAPIを使用"^]



==== vPCピアリングのサポート

同じリージョンにあるに 生成AIインフラを導入し、同じAWSアカウントを使用できるようになりましlink:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["ピア関係にある仮想プライベートクラウド（VPC）"^]た。AIエンジンをVPCに導入してから、ピアVPCにナレッジベースを作成し、ピアVPCにあるAmazon FSx for NetApp ONTAPファイルシステムを選択できます。

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["生成AIナレッジベースの作成"]



=== セットアップと管理



==== ONTAP CLIコマンドについて、AIによって生成されたエラー応答がCloudShellで報告される

CloudShellを使用している場合、ONTAP CLIコマンドを発行してエラーが発生するたびに、失敗の説明、失敗の原因、詳細な解決策を含むAI生成のエラー応答を取得できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用"]



==== IAM：SimulatePermissionPolicy権限の更新

AWSアカウントのクレデンシャルを追加したり、生成AIワークロードなどの新しいワークロード機能を追加したりするときに、ワークロードファクトリコンソールから権限を管理できるようになりまし `iam:SimulatePrincipalPolicy`た。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]



== 2025年3月02日



=== VMwareワークロード



==== Amazon EC2 Migration Advisorの機能強化

このリリースのVMware向けBlueXP  ワークロードファクトリでは、Amazon EC2 Migration Advisorのエクスペリエンスが次のように改善されています。

* *推定インスタンスタイプ*：Migration Advisorで環境の要件を確認し、VMごとに推定Amazon EC2インスタンスタイプを提供できるようになりました。移行アドバイザの「スコープ」ステップで、各VMの推定インスタンスタイプを含めるように選択できます。
* * Amazon EBSボリュームの推奨機能*：移行アドバイザーは、特定のリージョンの容量やパフォーマンスのニーズに応じて、Amazon FSx for NetApp ONTAPではなくAmazon Elastic Block Store（EBS）にデータボリュームを移行することを推奨できるようになりました。
* *ファイルシステムの自動割り当ての強化*：Amazon FSx for NetApp ONTAPファイルシステムの割り当てが改善され、コストの最適化とスループットの最小化が実現しました。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["移行アドバイザを使用してAmazon EC2の導入計画を作成"]



== 2025年02月02日



=== セットアップと管理



==== BlueXP  Workload FactoryコンソールでCloudShellを使用可能

CloudShellは、BlueXP  ワークロードファクトリコンソールのどこからでも使用できます。CloudShellを使用すると、BlueXP  アカウントで提供したAWSとONTAPのクレデンシャルを使用して、シェルに似た環境でAWS CLIコマンドまたはONTAP CLIコマンドを実行できます。

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["CloudShellを使用"]



==== データベースの権限の更新

データベースの_read_modeで次の権限を使用できるようになりました `iam:SimulatePrincipalPolicy`。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["アクセス権参照変更ログ"]



== 2024年12月01日

<stdin> 内の未解決のディレクティブ - include::_include/workload-builders.adoc[] :leveloffset: +1



=== ビルダーワークロードの初回リリース

BlueXP  Workload Factory for Buildersは、ソフトウェアバージョンの消費とアクセスを簡素化し、カスタムツールやスクリプトの必要性を排除します。ソフトウェアバージョンをPerforce Helix Coreと統合されたインスタントクローンとして使用し、開発プロセスに便利なワークスペースとして使用できるため、時間とリソースを節約できます。

初期リリースには、プロジェクトとワークスペースを管理し、Codeboxを使用してアクションを自動化する機能が含まれています。また、BuildersとPerforce Helix Coreを統合することで、プロジェクトごとに異なるバージョンを管理し、すばやく切り替えることができます。
