= 容量管理の自動化の強化
:allow-uri-read: 




=== 容量管理の自動化の強化

容量の自動管理を有効にすると、BlueXP  ワークロードファクトリでは、ファイルシステムが容量のしきい値に達したかどうかが2時間ごとではなく30分ごとにチェックされるようになりました。

ワークロードファクトリは、ボリューム内の使用可能なinodeもスキャンし、設定された容量の自動管理しきい値に従ってその数を増やします。

容量のしきい値に達しても、プロビジョニングIOPSの設定は影響を受けなくなりました。



=== 変更不可のSnapshot

特定の保持期間にわたってSnapshotをロックし、変更不可にすることができるようになりました。ロックにより、スナップショットへの不正アクセスや悪意のある削除を防止できます。Snapshotポリシーの作成時、手動でのSnapshotの作成時、およびSnapshotの作成後に、変更不可のSnapshotを有効にすることができます。



=== 不変ファイルの更新

変更不可のファイル設定に対して、保持ポリシー、保持期間、自動コミット期間、およびボリュームアペンドモードを変更できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["変更不可ファイルの管理"^]



=== データレプリケーションの機能拡張

* アカウント間レプリケーション：2つのAWSアカウント間のレプリケーションは、BlueXP  ワークロードファクトリコンソールとレプリケーション管理でサポートされています。
* データ保護ボリュームのレプリケーション：ボリュームがレプリケートされたボリュームからレプリケートされる場合、データ保護ボリュームでカスケードレプリケーションがサポートされるようになりました。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["データ保護ボリュームをレプリケートする"]

* レプリケーションの一時停止と再開：ソースボリュームからデスティネーションボリュームへのスケジュールされたレプリケーション更新を一時停止（休止）し、準備ができたらレプリケーションスケジュールを再開できます。一時停止中は、ソースボリュームとデスティネーションボリュームが独立し、デスティネーションボリュームは読み取り専用から読み書き可能に移行します。
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["レプリケーション関係の一時停止と再開"]





=== TrackerのCloudShellイベント

これで、TrackerでCloudShellイベントを追跡できるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Trackerを使用して運用を監視および追跡する方法をご確認ください"]
