= PostgreSQLの高可用性構成
:allow-uri-read: 




=== PostgreSQLの高可用性構成

PostgreSQLサーバにハイアベイラビリティ（HA）構成を導入できるようになりました。

link:https://review.docs.netapp.com/us-en/workload-databases_explore-savings-updates/create-postgresql-server.html["PostgreSQLサーバの作成"]



=== PostgreSQLサーバ作成のTerraformサポート

CodeboxからTerraformを使用してPostgreSQLをデプロイできるようになりました。

* link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["PostgreSQLデータベースサーバの作成"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["コードボックスからTerraformを使用"]




=== ローカルSnapshotスケジュールの耐障害性評価

データベースワークロードに新しい耐障害性評価を提供します。Microsoft SQL Serverインスタンスのボリュームにスケジュールされた有効なSnapshotポリシーが設定されているかどうかを評価します。Snapshotは、データのポイントインタイムコピーであり、データ損失が発生した場合にデータベース環境の耐障害性を維持するのに役立ちます。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



=== MAXDOPによるデータベースワークロードの修正

BlueXP  Workload Factory for Databasesでは、最大並列化(MAXDOP)サーバ構成の修復がサポートされるようになりました。MAXDOP設定が最適でない場合、BlueXP  Workload Factoryに設定を最適化させることができます。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["構成を最適化"]



=== コスト削減分析レポートをEメールで送信

Amazon Elastic Block StoreとFSx for Windowsファイルサーバのストレージ環境でFSx for ONTAPと比較してコスト削減を検討している場合、推奨レポートを自分、チームメンバー、お客様にEメールで送信できるようになりました。
