= BlueXPワークロードファクトリー通知サービスのサポート
:allow-uri-read: 




=== BlueXPワークロードファクトリー通知サービスのサポート

BlueXP ワークロードファクトリー通知サービスを使用すると、ワークロードファクトリーは BlueXP アラートサービスまたは Amazon SNS トピックに通知を送信できます。BlueXPアラートに送信された通知は、BlueXP アラートパネルに表示されます。ワークロードファクトリーが Amazon SNS トピックに通知を発行すると、トピックのサブスクライバー（ユーザーや他のアプリケーションなど）は、トピックに設定されたエンドポイント（E メールや SMS メッセージなど）で通知を受け取ります。

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["BlueXPワークロードファクトリー通知を構成する"^]

ワークロード ファクトリーは、データベースに対して次の通知を提供します。

* よく設計されたレポート
* ホストの展開




=== インスタンス登録のオンボーディング強化

Workload Factory for DatabasesAmazon FSx for NetApp ONTAPストレージで実行されているインスタンスを登録するためのオンボーディング プロセスが改善されました。登録するインスタンスを一括で選択できるようになりました。インスタンスが登録されると、ワークロード ファクトリー コンソール内でデータベース リソースを作成および管理できるようになります。

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["インスタンス管理"]



=== Microsoft マルチパス I/O タイムアウト設定の分析と修正

データベース インスタンスの well-architected ステータスに、Microsoft Multipath I/O (MPIO) タイムアウト設定の分析と修正が含まれるようになりました。  MPIO タイムアウトを 60 秒に設定すると、フェイルオーバー中の FSx for ONTAPストレージの接続性と安定性が確保されます。  MPIO 設定が適切に設定されていない場合、ワークロード ファクトリーは MPIO タイムアウト値を 60 秒に設定する修正を提供します。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["ワークロードファクトリーで適切に設計されたデータベース構成を実装する"]



=== インスタンスインベントリのグラフィックの強化

インスタンス インベントリ画面では、スループットや IOPS などのさまざまなリソース使用率グラフに 7 日間のデータが表示されるようになり、ワークロード ファクトリー コンソールから SQL ノードのパフォーマンスをより効率的に監視できるようになりました。  SQL ノードから収集されたパフォーマンスメトリクスは Amazon CloudWatch に保存され、Logs Insights や環境内の他の分析サービスとの統合に使用できます。

インベントリ内のインスタンスとデータベースのタブでは、保護の説明と視覚化が強化されました。



=== ワークロードファクトリーでの Windows 認証のサポート

現在、ワークロード ファクトリーは、インスタンスを登録し、管理機能のメリットを享受するために、Windows 認証ユーザーを使用した SQL Server 認証をサポートしています。

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["データベースのワークロードファクトリーにインスタンスを登録する"]
