= スケールアウトシステムの容量を自動管理
:allow-uri-read: 




=== スケールアウトシステムの容量を自動管理

Workload factoryでは、ボリューム内の使用可能なinodeがスキャンされ、設定された容量の自動管理しきい値に従ってその数が増加します。この機能では、スケールアウトシステムの容量の自動管理がサポートされます。容量の自動管理の一環として、inode管理を有効にすることができます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["容量の自動管理を有効にする"]



=== FlexGroupリバランシングAPI

BlueXP  ワークロード工場では、FlexGroupリバランシングAPIがリリースされています。このAPIを使用すると、FlexGroup内のデータをリバランシングするプランを実行できます。リバランシングを実行すると、メンバーボリュームにデータが均等に再配分されます。

link:https://console.workloads.netapp.com/api-doc["BlueXP  ワークロードファクトリAPIドキュメント"]



=== データの複製フォームにはユースケースが含まれる

データの複製フォームには、フォームへの入力を容易にするためのユースケースが含まれるようになりました。データレプリケーションのユースケースとして、移行、ホットディザスタリカバリ、コールドディザスタリカバリ、アーカイブなどのいずれかを選択します。ユースケースを選択したあと、Workload Factoryではベストプラクティスに従った値が推奨されます。事前選択された値を受け入れるか、フォームの値をカスタマイズできます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["データのレプリケート"]



=== データ階層化ポリシーの用語の変更

ボリュームの作成時、データレプリケーション時、または既存の階層化ポリシーの更新時に階層化ポリシーを選択すると、階層化ポリシーを表す新しい用語が追加されます。

* バランス（自動）_
* _コスト最適化（すべて）_
* _パフォーマンスを最適化（Snapshotのみ）_

