= 1回限りの評価
:allow-uri-read: 




=== 1回限りの評価

Workload Factory では、新しいデプロイメント、移行後、トラブルシューティングなど、必要なときにいつでもデータベース デプロイメントの構成を分析するための 1 回限りの評価が提供されるようになりました。デプロイメント構成を最適化し、ベスト プラクティスに準拠するのに役立つ推奨事項が得られます。これは、セットアップ プロセスを完全に実行せずに、適切に設計された機能を使用できる機会です。Workload Factory にクレデンシャルを保存したり、データベース リソースを登録したり、外部接続を設定したりすることなく、データベースを評価できます。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["データベース導入の 1 回限りの評価を実行する"]



=== Microsoft SQL Server上のAlways On可用性グループおよびOracle上のData Guardの登録サポート

Always On 可用性グループ（AOAG）展開モデルを使用した Microsoft SQL Server インスタンスと、Data Guard 展開モデルを使用した Oracle データベースを、NetApp Workload Factory のデータベース ワークロードで検出および登録できるようになりました。この機能強化により、Workload Factory コンソール内での SQL Server および Oracle リソースの管理が向上します。

AOAG インスタンスと Data Guard データベースを登録すると、リソースの詳細の表示やエラー ログの分析など、Workload Factory for Databases のさまざまな機能を利用できるようになります。

Workload Factory for Databasesは、AOAGデプロイメントモデルを使用したMicrosoft SQL Serverインスタンスの優れたアーキテクチャの分析もサポートしています。可用性グループ内のSQL Serverインスタンスの構成を分析し、デプロイメント構成を最適化してベストプラクティスに準拠するための推奨事項を受け取ることができます。この機能を有効にするには、AOAGインスタンスを登録してください。

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html#register-a-sql-server-instance["Workload Factory for Databases にリソースを登録する"]



=== Oracle 向けの Well-Architected 分析

Well-Architected 分析には、Oracle の *オペレーティング システム パッチ* が含まれており、オペレーティング システムに最新のパッチが適用されているかどうかを確認し、そのインストール方法を案内します。

さらに、Oracle の Well-Architected 分析では、ストレージ レイアウトなどの構成が他の構成に依存している場合に通知されます。通知には、リンクされた構成を最適化するためのアクションが示され、提供されるすべての推奨事項が最適になります。

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Workload Factory で Well-Architected データベース構成を実装する"]



=== Oracle オンプレミス データベース環境のコスト分析と移行計画

Workload Factory for Databasesは、OracleオンプレミスデータベースのAmazon FSx for NetApp ONTAPへの移行を分析し、計画を支援します。節約計算ツールを使用すると、Oracleオンプレミスデータベース環境をクラウドで実行する際のコストを見積もり、オンプレミスデータベース環境をクラウドに移行するための推奨事項を確認できます。

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["オンプレミスデータベース環境の節約方法を見る"]



=== Workload Factory で新しい Ask Me ブックマークが利用可能になりました

Workload Factory コンソールのすべての画面に新しい Ask Me ブックマークを追加しました。この改善により、ヘルプが必要なときにいつでも Ask Me に簡単かつ迅速にアクセスできるようになります。Ask Me は AI アシスタントであり、独自のワークロード環境について質問したり、環境から直接パーソナライズされた分析情報を取得したり、以前の会話を参照したりすることができます。

新しいブックマークをクリックすると、どのページからでも Ask Me を開くことができます。現在の作業を中断することなく、サイドパネルで Ask Me を起動し、現在行っている作業に関連する簡単な説明と推奨事項を提供します。

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Ask Meの詳細"^]
