= すべての FSx for ONTAP システムで新しいwell-architectedダッシュボードが利用可能になりました
:allow-uri-read: 




[[new-well-architected-dashboard-available-for-all-fsx-for-ontap-systems]]
=== すべての FSx for ONTAP システムで新しいwell-architectedダッシュボードが利用可能になりました

ウェルアーキテクテッド分析が、NetApp Workload Factory の新しいウェルアーキテクテッドダッシュボードから、FSx for ONTAP ファイルシステムで利用できるようになりました。新しいダッシュボードでは、アカウントやリージョンをまたがるすべてのファイルシステムとその構成を一元的に確認できます。ファイルシステムから「Well-architected」タブにアクセスすると、ポップアップ通知が表示されます。Workload Factory の左側のナビゲーションメニューから「Well-architected」を選択すると、新しいダッシュボードにアクセスできます。

特定のファイルシステムのWell-architected分析には、引き続きアクセスできます。また、ストレージの「Well-architected」メニューオプションからもアクセスできます。



[[new-widgets-added-to-the-storage-dashboard]]
=== ストレージダッシュボードに新しいウィジェットが追加されました

ストレージダッシュボードに、ストレージの使用状況を把握し、最適化する方法を見つけるのに役立つ2つの新しいウィジェットが追加されました。

* *検出された上位ワークロード* タグ付けサービスによって環境全体で検出されたワークロードデータを表示します。ボリュームやブロックデバイスなどの関連する FSx リソースを含む、信頼度スコアが 80% を超えるワークロードを表示します。各ワークロードには、その名前、リソース数、プロビジョニングされた容量、および使用済み容量が表示されます。リソース数（デフォルト）、プロビジョニング済み容量、または使用済み容量で並べ替えることで、最大のワークロードをすばやく特定し、ストレージの使用パターンを把握できます。
* *AIを活用した洞察と観察* 管理対象資産に関するAI生成の洞察を表示します。このウィジェットは、選択した範囲内の資産データを分析し、容量、パフォーマンス、データ保護、レプリケーション、コスト削減、ストレージの傾向など、主要な分野における上位3つの発見事項を強調表示します。


各インサイトには、概要、詳細な調査結果、および推奨アクションが含まれています。インサイトを展開すると、詳細を確認し、深刻度、パフォーマンスの改善、コスト削減の機会に基づいて問題の優先順位を付けることができます。



[[workload-tagging]]
=== ワークロードタグ付け



==== ワークロードタグ付けのためのAWS Systems Managerとの統合

ワークロードタグ付けサービスは、AWS Systems Managerと連携して、ホストインベントリデータに詳細情報を追加できるようになりました。Workload Factoryは、SSMインベントリ情報を収集および処理することで、ワークロードの識別と分類をより適切に行えるようになりました。AWS SSM属性もタグ付けプロセスに含まれており、ワークロード検出の精度向上に役立てられています。

適切に設計されたダッシュボード内のボリューム関連の設定すべてにおいて、リソーステーブルに「ワークロード」列が追加されました。この列は、Workload Factory が各ボリュームに関連付けているワークロードを示しています。



[[workload-tagging-and-ai-features]]
=== ワークロードタグ付けとAI機能

管理者がAI機能を無効にした場合、ワークロードにはタグ付けされません。Workload Factoryアカウントの設定でAI機能が無効になっている場合、タグ付けサービスはストレージリソース上のワークロードを識別または分類しません。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-genai-features.html["AI管理について学ぶ"^]。



[[explore-savings-snapshot-calculation-improvement]]
=== 節約額のスナップショット計算の改善点を確認する

「Explore savings now」では一貫したスナップショット容量計算が使用されるようになったため、FSx for ONTAP の節約額の見積もりに追加のスナップショット容量プール要件が正しく考慮されます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/explore-savings.html["Amazon Elastic Block Store、FSx for Windows File Server、Elastic File System のストレージ環境におけるコスト削減効果をご確認ください。"]



==== レプリケーション遅延データをCSVファイルにエクスポートする

レプリケーション遅延データをCSVファイルにエクスポートして、スプレッドシートでデータを分析したり、他のユーザーと共有したりできるようになりました。



[[s3-access-point-events]]
=== S3アクセスポイントイベント

S3アクセスポイントのイベントを、設定したスケジュールに従ってSNSトピックに送信できるようになりました。各アップデートには、前回のアップデート以降に発生したすべてのイベントが含まれます。

S3 イベントの通知を設定するには、link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-s3-access-points.html["S3アクセスポイントを編集する"] *Journal table* セクションで *Send S3 events by SNS* を選択します。
