= すべての FSx for ONTAP システムで新しいwell-architectedダッシュボードが利用可能になりました
:allow-uri-read: 




=== すべての FSx for ONTAP システムで新しいwell-architectedダッシュボードが利用可能になりました

ウェルアーキテクテッド分析が、NetApp Workload Factory の新しいウェルアーキテクテッドダッシュボードから、FSx for ONTAP ファイルシステムで利用できるようになりました。新しいダッシュボードでは、アカウントやリージョンをまたがるすべてのファイルシステムとその構成を一元的に確認できます。ファイルシステムから「Well-architected」タブにアクセスすると、ポップアップ通知が表示されます。Workload Factory の左側のナビゲーションメニューから「Well-architected」を選択すると、新しいダッシュボードにアクセスできます。

特定のファイルシステムのWell-architected分析には、引き続きアクセスできます。また、ストレージの「Well-architected」メニューオプションからもアクセスできます。



=== 優れたアーキテクチャ分析における新たな推奨事項

Workload Factory は、FSx for ONTAP ファイルシステムの適切なアーキテクチャ分析に以下の構成を含めるようになりました：

* ホストをフェイルオーバーノードに接続：アクティブ / パッシブ FSx for ONTAP ファイルシステムでホストがフェイルオーバーノードに接続されているかどうかを確認し、信頼性向上のためにホストをフェイルオーバーノードに接続することを推奨します。
* ホストを優先ノードに接続する：ホストが優先ノードを使用してブロックデバイスに接続されているかどうかを確認し、パフォーマンス効率のためにホストを優先ノードに接続することを提案します。




=== ボリュームエクスプローラー

Volumes Explorer は、NetApp Workload Factory のすべてのボリュームをシンプルに検索可能なビューで表示します。どのボリュームがブロックワークロードまたはファイルワークロードに使用されているかをすばやく確認できます。各ボリュームの論理サイズ、物理的な使用容量、およびストレージ効率化機能（圧縮、重複排除、コンパクション）を使用しているかどうかを確認できます。名前、ステータス（利用可能／失敗）、レイテンシ、サイズ、使用容量、および保護機能でフィルタリングおよび並べ替えを行います。



=== レプリケーション遅延の改善



==== レプリケーション遅延に関するメール通知機能の強化

レプリケーション遅延に関するメール通知に、影響を受けるリレーションシップに関する詳細情報が含まれるようになりました。この通知により、影響を受けるリレーションシップを迅速に特定し、Workload Factory コンソールで詳細を確認できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["レプリケーション遅延に関する通知を有効にする"]



==== レプリケーション遅延データをCSVファイルにエクスポートする

レプリケーション遅延データをCSVファイルにエクスポートして、スプレッドシートでデータを分析したり、他のユーザーと共有したりできるようになりました。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["レプリケーションの遅延を追跡する"]



=== ブロックデバイス作成機能の強化

Workload Factoryは、ボリュームスナップショットからのブロックデバイスの作成をサポートしています。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Workload Factory でボリュームスナップショットからブロックデバイスを作成する"]
