= ボリュームエクスプローラー
:allow-uri-read: 




[[volumes-explorer]]
=== ボリュームエクスプローラー

Volumes Explorer は、NetApp Workload Factory のすべてのボリュームをシンプルに検索可能なビューで表示します。どのボリュームがブロックワークロードまたはファイルワークロードに使用されているかをすばやく確認できます。各ボリュームの論理サイズ、物理的な使用容量、およびストレージ効率化機能（圧縮、重複排除、コンパクション）を使用しているかどうかを確認できます。名前、ステータス（利用可能／失敗）、レイテンシ、サイズ、使用容量、および保護機能でフィルタリングおよび並べ替えを行います。



[[enhanced-email-notifications-for-replication-delays]]
=== レプリケーション遅延に関するメール通知機能の強化

レプリケーション遅延に関するメール通知に、影響を受けるリレーションシップに関する詳細情報が含まれるようになりました。この通知により、影響を受けるリレーションシップを迅速に特定し、Workload Factory コンソールで詳細を確認できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["レプリケーション遅延に関する通知を有効にする"]



[[block-device-creation-enhancement]]
=== ブロックデバイス作成機能の強化

Workload Factoryは、ボリュームスナップショットからのブロックデバイスの作成をサポートしています。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Workload Factory でボリュームスナップショットからブロックデバイスを作成する"]



[[workload-tagging-for-volumes-and-block-devices]]
=== ボリュームとブロックデバイスのワークロードタグ付け

Workload Factoryは、ボリュームとブロックデバイスを、その主要なワークロードまたはアプリケーションに基づいて識別し、タグ付けするようになりました。Microsoft SQL ServerやOracle Databaseなどの定義済みワークロードタグを割り当てるか、アプリケーション用にカスタムタグを作成することができます。タグは個々のリソースに適用することも、接続されているストレージリソースに継承させることもできます。これにより、ストレージ構成をワークロードの要件に合わせ、インシデントの影響を把握し、より効果的にトラブルシューティングを行うことができます。
