= ホームページには、ストレージに関する適切に設計された問題と EMS イベントが含まれています
:allow-uri-read: 




=== ホームページには、ストレージに関する適切に設計された問題と EMS イベントが含まれています

NetApp Workload Factory のホームページには、ワークロードに関する適切に設計された問題と FSx for ONTAP Emergency Management System（EMS）イベントが表示される Focus タイルがあります。そこから、Storage ワークロードに移動して、ストレージ環境内のすべての FSx for ONTAP ファイル システムの適切に設計されたステータスまたはイベントを表示できます。



=== S3 アクセスポイントを使用したオンプレミスデータレプリケーションのサポート

Workload Factory は、AWS GenAI、ML、分析との統合のために、オンプレミス ONTAP データのクラウドへのレプリケーションをサポートしています。S3 アクセス ポイントを使用して、オンプレミス データを NFS または SMB/CIFS ボリュームにレプリケートできます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["S3 アクセス ポイントを使用してオンプレミス データを複製する"]



=== Storage の S3 アクセス ポイントの機能強化

NetApp Workload Factory のストレージワークロードにおける S3 アクセスポイント管理機能にいくつかの機能強化が行われました。S3 アクセスポイントのネットワーク構成の詳細を入力し、S3 アクセスポイントタグを追加できます。追加の機能強化には、S3 バケットの詳細を表示する機能や、S3 アクセスポイントを管理するための追加のアクションを実行する機能が含まれます。



==== S3 バケットの詳細は Storage で利用可能

S3アクセスポイントのメタデータを有効にすると、NetApp Workload Factoryは、AWS S3バケットを自動的にスキャンし、S3テーブルにデータを入力して、すべてのオブジェクト、そのメタデータ、属性、タグの明確なスナップショットを提供します。これらの詳細にアクセスすることで、運用上のオーバーヘッドを削減しながら、責任のあるデータの制御、可視性、信頼性を維持することができます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["FSx for ONTAP ファイルシステムの S3 アクセスポイントの詳細を表示"]



==== S3 アクセス ポイントの追加管理操作

NetApp Workload Factory は、S3 アクセス ポイントの追加の管理操作を提供します。NetApp Workload Factory インターフェースから、アクセス ポイントの詳細を表示したり、既存の S3 アクセス ポイントを変更したり、S3 アクセス ポイント タグを追加または削除したりできるため、オブジェクト ストレージ管理タスクを効率化できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["NetApp Workload FactoryでS3アクセスポイントを管理する"]



=== Well-Architected 分析の更新

Workload Factory は、次の構成について FSx for ONTAPファイル システムを分析します。

* キャッシュ ボリューム サイズの最適化：最適なサイズを維持し、ホット データにキャッシュを集中させて効率を最大限に高めるために、キャッシュ ボリュームでボリュームの自動サイズ調整とスクラビングが有効になっているかどうかを確認します。
* 非アクティブなブロックデバイス：7 日間連続して使用されていないブロックデバイスのデータのアーカイブまたはブロックデバイスの削除を推奨します。
* Storage VM 論理レポート：Storage VM のデフォルトのレポート設定が論理に設定されているかどうかを確認します。これにより、ボリューム レベルでのストレージ使用状況の可視性が向上します。




=== ブロックデバイス用の追加カード

ブロック デバイスの使用状況と保護ステータスを迅速に把握できるように、Storage ワークロードの Block devices タブに 3 つの新しいカードが追加されました。

* ストレージ効率：使用済みおよび使用可能なストレージ容量を表示します。使用済み容量は、SSD および容量プールのストレージ階層別に分類されます。
* 保護されたデバイス：スナップショット、リモートレプリケーション、NetApp Autonomous Ransomware Protection（ARP/AI）、およびバックアップを使用するブロックデバイスの割合を表示します。
* 孤立デバイス：7 日間連続して使用されていないブロック デバイスがあるかどうかを表示し、未使用のリソースを効果的に識別して管理するのに役立ちます。ここから、link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html#archive-the-data-of-an-inactive-block-device["未使用のブロックデバイスのスペースを再利用する"]。




=== イニシエータグループの作成と管理のサポート

NetApp Workload Factoryは、FSx for ONTAPファイルシステムのブロックストレージ用イニシエータグループ（igroup）の作成と管理をサポートします。イニシエータグループは、ブロックデバイス（LUN）をアクセスが許可されたコンピューティングリソースに接続し、SAN環境のブロックストレージにアクセス許可レイヤーを提供します。

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-igroup.html["NetApp Workload Factoryでイニシエータグループを作成する"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-igroups.html["NetApp Workload Factory で既存のイニシエーターグループを管理する"]

