= すべての FSx for ONTAP システムで新しいwell-architectedダッシュボードが利用可能になりました
:allow-uri-read: 




[[new-well-architected-dashboard-available-for-all-fsx-for-ontap-systems]]
=== すべての FSx for ONTAP システムで新しいwell-architectedダッシュボードが利用可能になりました

ウェルアーキテクテッド分析が、NetApp Workload Factory の新しいウェルアーキテクテッドダッシュボードから、FSx for ONTAP ファイルシステムで利用できるようになりました。新しいダッシュボードでは、アカウントやリージョンをまたがるすべてのファイルシステムとその構成を一元的に確認できます。ファイルシステムから「Well-architected」タブにアクセスすると、ポップアップ通知が表示されます。Workload Factory の左側のナビゲーションメニューから「Well-architected」を選択すると、新しいダッシュボードにアクセスできます。

特定のファイルシステムのWell-architected分析には、引き続きアクセスできます。また、ストレージの「Well-architected」メニューオプションからもアクセスできます。



[[volumes-explorer]]
=== ボリュームエクスプローラー

Volumes Explorer は、NetApp Workload Factory のすべてのボリュームをシンプルに検索可能なビューで表示します。どのボリュームがブロックワークロードまたはファイルワークロードに使用されているかをすばやく確認できます。各ボリュームの論理サイズ、物理的な使用容量、およびストレージ効率化機能（圧縮、重複排除、コンパクション）を使用しているかどうかを確認できます。名前、ステータス（利用可能／失敗）、レイテンシ、サイズ、使用容量、および保護機能でフィルタリングおよび並べ替えを行います。



[[enhanced-email-notifications-for-replication-delays]]
=== レプリケーション遅延に関するメール通知機能の強化

レプリケーション遅延に関するメール通知に、影響を受けるリレーションシップに関する詳細情報が含まれるようになりました。この通知により、影響を受けるリレーションシップを迅速に特定し、Workload Factory コンソールで詳細を確認できます。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["レプリケーション遅延に関する通知を有効にする"]



[[block-device-creation-enhancement]]
=== ブロックデバイス作成機能の強化

Workload Factoryは、ボリュームスナップショットからのブロックデバイスの作成をサポートしています。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Workload Factory でボリュームスナップショットからブロックデバイスを作成する"]
